# Enzyme Function Prediction using Neural Networks (EC Level 3)

In this homework, we will design several neural networks with different architectures for **Enzyme Function Prediction** from protein sequences.

**Enzyme Commission (EC) numbers** constitute a numerical classification scheme for enzymes, based on the chemical reactions they catalyze. Unlike protein families (Pfam) which are often defined by sequence similarity, EC numbers describe the **functional role** of a protein (e.g., *what* reaction it performs). This makes the task challenging, as the model must learn complex structure-function relationships where different sequences might catalyze similar reactions (convergent evolution).

In this problem, each protein in the training or test set is labeled with exactly one **Level-3 EC number** derived from the **UniProtKB/Swiss-Prot** database. The EC number is a hierarchical string (e.g., `2.7.1.-`), where:

* **Level 1**: Main Class (e.g., `2` = Transferases)
* **Level 2**: Subclass (e.g., `2.7` = Transferring phosphorus-containing groups)
* **Level 3**: Sub-subclass (Target of this task) (e.g., `2.7.1` = Phosphotransferases with an alcohol group as acceptor)



There are a total of 183 distinct functional categories (Level-3) appearing in the dataset. Although many enzymes are "promiscuous" (catalyzing multiple different reactions), we simplify the problem by filtering for single-function enzymes and treating it as a single-label multi-class classification task.

To begin with, run the following cell to download the training and test data.

> ### Resource Warning: OOM & Slow Training
>
> You may encounter **`CUDA out of memory`** errors or find the training process slow due to the size of the models.
>
> **For Students:** Google Colab offers **free compute units** for users with student email addresses. This provides access to high-RAM GPUs such as A100, R100.
> **[Click here to apply for Student Compute Units](https://colab.research.google.com/signup?utm_source=resource_tab&utm_medium=link&utm_campaign=want_more_resources)**

Import the necessary packages:

In [169]:
# export
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json, os, time
from sklearn.model_selection import train_test_split
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import Dataset, DataLoader
import numpy as np
from tqdm import tqdm
import math
##### DO NOT MODIFY ANYTHING IN THIS CELL #####

Load the training data and take a look at the sequences and EC number labels

In [170]:
with open('labels.json') as f:
    label_list = json.load(f)

# Create mapping from Label string to Integer index
label2idx = {label: idx for idx, label in enumerate(label_list)}
print(f'Number of Subcellular Locations: {len(label_list)}')

Number of Subcellular Locations: 183

In [171]:
df_train = pd.read_csv('train.csv')
sequences = df_train['Sequence'].tolist()
labels = df_train['Label'].tolist()
df_train.head()

,Entry,Sequence,EC number,Label
0,Q61176,MSSKPKSLEIIGAPFSKGQPRGGVEKGPAALRKAGLLEKLKETEYD...,3.5.3.1,3.5.3
1,Q21MC3,MTDSKSNSNSPSLSYKDAGVDIDAGNALVERIKSVAKRTRRPEVMA...,6.3.3.1,6.3.3
2,Q85WU9,MAHSVKIYDTCIGCTQCVRACPTDVLEMIPWEGCKAKQIASAPRTE...,1.97.1.12,1.97.1
3,B7GGC6,MFMSQFHATTIFAIRHQGKGAMAGDGQVTFGNAVVMKHTARKIRKL...,3.4.25.2,3.4.25
4,Q32067,KRSLRDLGIPVNQIIPEGGSLKYLKDLPRAWFNIVPYREVGLMTAI...,1.3.7.7,1.3.7

In [172]:
df_val = pd.read_csv('val.csv')
seq_val = df_val['Sequence'].tolist()
label_val = df_val['Label'].tolist()
df_val.head()

    Entry                                           Sequence EC number   Label
0  Q16595  MWTLGRRAVAGLLASPSPAQAQTLTRVPRPAELAPLCGRRGLRTDI...  1.16.3.1  1.16.3
1  Q1CHE5  MQLNIPTWLTLFRVVLIPFFVLAFYLPFVWAPMVCAIIFVFAAATD...   2.7.8.5   2.7.8
2  P60586  MDFNLNDEQELFVAGIRELMASENWEAYFAECDRDSVYPERFVKAL...  1.3.8.13   1.3.8
3  Q99TL8  MNGVYHIMNNEYPYSADEVLHKAKSYLSADEYEYVLKSYHIAYEAH...   2.7.6.5   2.7.6
4  Q9X794  MVAPLAEVDPDIAELLGKELGRQRDTLEMIASENFVPRSVLQAQGS...   2.1.2.1   2.1.2

In [173]:
print(f'Training samples: {len(sequences)}')
print(f'Validation samples: {len(seq_val)}')

Training samples: 18094
Validation samples: 3877

In [174]:
print("num_classes from json:", len(label_list))
print("train label examples:", df_train["Label"].head(10).tolist())

num_classes from json: 183
train label examples: ['3.5.3', '6.3.3', '1.97.1', '3.4.25', '1.3.7', '1.14.19', '2.7.2', '4.99.1', '3.1.13', '1.20.4']

## Task 1: One-hot tokenizer

Protein sequences consist of a list of amino acids. There are 20 types of standard amino acids. We need to transform (tokenize) protein sequences into tensors so that neural networks can take them as inputs. A straightforward way to tokenize protein sequences is to use one-hot encoding ([wiki link](https://en.wikipedia.org/wiki/One-hot)). In this task you need to complete the function `one_hot_encode` which takes a protein sequence (a string of amino acids) of length $L$ and output an one-hot-encoded tensor of shape $L\times 20$.

In [175]:
# export
##### DO NOT MODIFY ANYTHING ABOVE THIS LINE #####

amino_acids = "ACDEFGHIKLMNPQRSTVWY"
aa_to_idx = {aa: i for i, aa in enumerate(amino_acids)}

# One-hot encoding function
def one_hot_encode(sequence, max_len=1000):
    sequence = sequence[:max_len]
    encoded = torch.zeros((len(sequence), 20))
    ######################################################################
    # TODO: Implement one-hot encoding loop
    # for i in range(len(sequence)):
    #     string_pos = amino_acids.find(sequence[i])
    #     encoded[i, string_pos] = 1
    idx = torch.tensor([aa_to_idx[aa] for aa in sequence if aa in aa_to_idx])
    encoded = F.one_hot(idx, num_classes=20).float()
    ######################################################################

    return encoded

In [176]:
test_seq = 'MWTLGRRAVAGLLASPSPAQAQTLTRVPRPAELAPLCGRRGLRTDI'
print(one_hot_encode(test_seq))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]])

With the one-hot tokenizer, we can design the dataset class. As you can see in the following cell, each data point returned by the dataset class contains three items: the one-hot encoded tensor, the length of the sequence, and the label. Since the length of the sequences in the dataset can vary, we provide the collate function that pads the sequences with zeros to the maximum length in the batch. You can pass this `collate_fn` to the `collate_fn` parameter of pytorch's DataLoader class to ensure the correct behaviour of batching.

In [177]:
# export
##### DO NOT MODIFY ANYTHING ABOVE THIS LINE #####

class ProteinDataset(Dataset):
    def __init__(self, sequences, labels, ec2idx):
        self.sequences = sequences
        self.labels = [ec2idx.get(ec, -1) for ec in labels]
        self.seq_tensors = [one_hot_encode(seq) for seq in tqdm(sequences, desc='Encoding sequences')]

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        seq_tensor = self.seq_tensors[idx]
        label = torch.tensor(self.labels[idx], dtype=torch.long)
        return seq_tensor, len(seq_tensor), label

# Collate function with padding
def collate_fn(batch):
    sequences, seq_lens, labels = zip(*batch)
    max_len = max(seq_lens)

    padded_sequences = pad_sequence(sequences, batch_first=True, padding_value=0)

    return padded_sequences, torch.tensor(seq_lens, dtype=torch.long), torch.tensor(labels, dtype=torch.long)

## Task 2: Transformer built from multi-head attention

In this task, you are required to implement a vanilla transformer encoder model for the EC number prediction task. You should construct the transformer model using blocks like `torch.nn.MultiheadAttention`, `torch.nn.Linear`, `torch.nn.LayerNorm`. Your transformer model should have the same architecture as the encoder module described in the paper [Attention is all you need](https://arxiv.org/abs/1706.03762). We recommend you to check PyTorch's documentation for the modules mentioned before.

## Task 2.1: Positional Encoding

Protein sequences are naturally ordered, and the relative position of amino acids often dictates the functional domain of an enzyme. However, the Multi-head Attention mechanism used in Transformers is "permutation-invariant," meaning it does not inherently understand the order of the input. To address this, we must inject **Positional Encoding (PE)** into the input embeddings.

Following the architecture in *Attention Is All You Need*, we use sine and cosine functions of different frequencies to generate unique position vectors:

$$PE_{(pos, 2i)} = \sin(pos / 10000^{2i/d_{model}})$$
$$PE_{(pos, 2i+1)} = \cos(pos / 10000^{2i/d_{model}})$$

Where:
* **$pos$**: The position of the amino acid in the sequence.
* **$i$**: The dimension index.
* **$d_{model}$**: The dimensionality of the hidden state (embedding dimension).



In this task, you need to implement the `PositionalEncoding` module.

In [178]:
# export
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        """
        Args:
            d_model: The dimension of the embeddings.
            max_len: The maximum length of the sequences.
        """
        super(PositionalEncoding, self).__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)

        ######################################################################
        # TODO: Implement the frequency term 'div_term'.
        # Hint: Use the formula exp(arange(0, d_model, 2) * -(log(10000.0) / d_model))
        # TODO: Populate the 'pe' matrix.
        # Apply sine to even indices (0::2) and cosine to odd indices (1::2).
        div_term = torch.exp(torch.arange(0, d_model, 2) * -(math.log(10000.0)) / d_model)
        pe[:, 0::2] = torch.sin(position*div_term)
        pe[:, 1::2] = torch.cos(position*div_term)
        ######################################################################

        self.register_buffer('pe', pe.unsqueeze(0))

    def forward(self, x):
        """
        Args:
            x: Input tensor of shape [batch_size, seq_len, d_model]
        """
        x = x + self.pe[:, :x.size(1), :]
        return x

## Task 2.2 Attention Classifier

In [179]:
class AttentionClassifier(nn.Module):
    def __init__(self, num_classes, embed_dim=64, num_heads=1, num_layers=1, ff_dim=128, dropout_p=0.1):
        super(AttentionClassifier, self).__init__()
        self.embedding = nn.Linear(20, embed_dim)
        self.attention_layers = None
        ######################################################################
        # TODO: implement the transformer block using multiheadattention, linear, and layernorm.
        self.pos_encoder = PositionalEncoding(embed_dim)
        self.dropout = nn.Dropout(p=dropout_p)

        self.attention_layers = nn.ModuleList()
        for _ in range(num_layers):
            attn = nn.MultiheadAttention(embed_dim=embed_dim, num_heads=num_heads, batch_first=True)
            ln1 = nn.LayerNorm(embed_dim)
            linear1 = nn.Linear(embed_dim, ff_dim)
            relu = nn.ReLU()
            linear2 = nn.Linear(ff_dim, embed_dim)
            ln2 = nn.LayerNorm(embed_dim)

            self.attention_layers.append(nn.ModuleList([attn, ln1, linear1, relu, linear2, ln2]))
        ######################################################################
        self.pooling = nn.AdaptiveAvgPool1d(1)
        self.fc = nn.Linear(embed_dim, num_classes)

    def forward(self, x, seq_lens):
        x = self.embedding(x)
        x = self.pos_encoder(x) # You can call the positional encoding function here
        x = self.dropout(x)
        max_len = x.shape[1]
        mask = torch.arange(max_len, device=x.device).expand(len(seq_lens), max_len) >= seq_lens.unsqueeze(1)
        mask = mask.to(x.device)

        for attn, ln1, linear1, relu, linear2, ln2 in self.attention_layers:
            attn_out, _ = attn(x, x, x, key_padding_mask=mask)
            attn_out = self.dropout(attn_out)
            x = ln1(x + attn_out)
            ff_out = linear2(relu(linear1(x)))
            ff_out = self.dropout(ff_out)
            x = ln2(x + ff_out)

        x = x.permute(0, 2, 1)
        x = self.pooling(x).squeeze(-1)

        return self.fc(x)

## Task 3: Transformer built from TransformerEncoder class

In this task, you will also implement a vanilla transformer model. Instead of constructing the model from small blocks like MultiheadAttention, you should use the wrapped module `torch.nn.TransformerEncoderLayer` and `torch.nn.TransformerEncoder` to directly build the model. We recommend you to check the documentation of these two modules to learn their usage.

In [180]:
class TransformerClassifier(nn.Module):
    def __init__(self, num_classes, embed_dim=128, num_heads=2, num_layers=2, ff_dim=256, dropout_p=0.1):
        super(TransformerClassifier, self).__init__()
        self.embedding = nn.Linear(20, embed_dim)
        self.encoder_layers = None
        ######################################################################
        # TODO: transformer block using TransformerEncoderLayer
        self.pos_encoder = PositionalEncoding(embed_dim)

        self.encoder_layers = nn.ModuleList()
        for _ in range(num_layers):
            encoder_layer = nn.TransformerEncoderLayer(
                d_model=embed_dim, 
                nhead=num_heads, 
                dim_feedforward=ff_dim,
                batch_first=True,
                dropout=dropout_p)
            self.encoder_layers.append(encoder_layer)
        # transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        ######################################################################
        self.pooling = nn.AdaptiveAvgPool1d(1)
        self.fc = nn.Linear(embed_dim, num_classes)

    def forward(self, x, seq_lens):
        x = self.embedding(x)
        x = self.pos_encoder(x) # You can call the positional encoding function here
        max_len = x.shape[1]
        mask = torch.arange(max_len, device=x.device).expand(len(seq_lens), max_len) >= seq_lens.unsqueeze(1)
        # print(mask.shape)
        mask = mask.to(x.device)
        ######################################################################
        # TODO: forward part of the transformer block
        for layer in self.encoder_layers:
            x = layer.forward(x, src_key_padding_mask=mask)
        ######################################################################
        x = x.permute(0, 2, 1)
        x = self.pooling(x).squeeze(-1)

        return self.fc(x)

## Task 4: 1D-CNN model

In this task, you are going to implement a model using 1D CNN layers. You can use PyTorch's `torch.nn.Conv1d` to construct the model. Note that for simplicity, you do not have to consider the padded part of the input tensor. Refer to PyTorch's documentation for the usage of `torch.nn.Conv1d`.

In [203]:
class CNNClassifier(nn.Module):
    def __init__(self, num_classes, embed_dim=64, num_filters=128, kernel_size=3, num_layers=3):
        super(CNNClassifier, self).__init__()
        self.embedding = nn.Linear(20, embed_dim)
        self.conv_layers = None
        ######################################################################
        # TODO: 1D convolutional layers
        self.conv_layers = nn.ModuleList()
        conv_layer_1 = nn.Conv1d(embed_dim, num_filters, kernel_size)

        self.conv_layers.append(conv_layer_1)
        self.conv_layers.append(nn.ReLU())

        for _ in range(num_layers-1):
            self.conv_layers.append(nn.Conv1d(num_filters, num_filters, kernel_size))
            self.conv_layers.append(nn.ReLU())
        ######################################################################
        self.pooling = nn.AdaptiveAvgPool1d(1)
        self.fc = nn.Linear(num_filters, num_classes)

    def forward(self, x, seq_lens):
        x = self.embedding(x).permute(0, 2, 1)
        ######################################################################
        # TODO: forward part of the CNN block
        for layer in self.conv_layers:
            x = layer.forward(x)
        ######################################################################
        x = self.pooling(x).squeeze(-1)
        return self.fc(x)

## Training the Neural Networks

Blocks marked with `# export` are required by the autograder and should not be modified.  
However, you are strongly encouraged to experiment with **all other code blocks**.

Examples of blocks you can safely adjust:
- Model initialization (e.g., hidden size, number of layers)
- The training loop (optimizer, learning rate, scheduler, gradient handling)
- The `train_model(...)` call and its arguments
- Data-related setup (batch size)

---

### Hyperparameter Tuning

You are encouraged to tune hyperparameters to improve validation performance.  
Common categories include:

**Optimization**
- Optimizer type  
- Learning rate and scheduler  
- Weight decay  

**Training setup**
- Batch size  
- Number of epochs  
- Early stopping  

**Model capacity**
- Hidden dimensions  
- Number of layers  
- Attention heads (Transformer)  
- CNN channels / kernel sizes  

**Regularization & stability**
- Dropout rates  
- Label smoothing  
- Gradient clipping (e.g., `clip_grad_norm_`)

If training becomes unstable (e.g., exploding gradients), gradient clipping may help.  

---

### Model Design Hints

- **Positional Encoding**: Helps the attention mechanism understand amino acid order, which is important for sequential structure modeling.

- **Dropout**: Applied after embedding and inside feed-forward blocks. Tuning dropout helps balance underfitting and overfitting.

- **Model Size**: Increasing embedding dimension or feed-forward size increases capacity but also memory usage.

- **Classification Head**: A multi-layer head (`Linear → ReLU → Dropout → Linear`) can be more expressive than a single linear layer.

- **Key Padding Mask**: Prevents attention from focusing on padded tokens, which is important for variable-length protein sequences.


**Be mindful of GPU memory — if you encounter OOM errors, reduce `batch_size` first before shrinking the model.**

Complete the function `train_model`.

In [182]:
import optuna
import torch
import torch.nn as nn
import torch.optim as optim

In [198]:
def train_model(model, train_dataset, val_dataset, num_classes, epochs=100, batch_size=256, lr=1e-3, patience=10, device='cuda:0', wd=0.01):
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, collate_fn=collate_fn)

    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=4)

    best_acc = 0
    patience_counter = 0
    best_ckpt = None

    for epoch in range(epochs):
        start_epoch = time.time()
        model.train()
        total_loss, correct, total = 0, 0, 0

        for sequences, seq_lens, labels in train_loader:
            sequences, seq_lens, labels = sequences.to(device), seq_lens.to(device), labels.to(device)
            outputs = None
            loss = None
            ######################################################################
            # TODO: Implement the training step
            optimizer.zero_grad()
            outputs = model.forward(sequences, seq_lens)
            loss = criterion(outputs, labels)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0, norm_type=2.0)
            optimizer.step()
            ######################################################################

            total_loss += loss.item()
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

        train_acc = correct / total

        # Validation
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for sequences, seq_lens, labels in val_loader:
                ######################################################################
                # TODO: model inference
                sequences, seq_lens, labels = sequences.to(device), seq_lens.to(device), labels.to(device)
                outputs = model(sequences, seq_lens)
                preds = torch.argmax(outputs, dim=1)
                ######################################################################
                correct += (preds == labels).sum().item()
                total += labels.size(0)

        val_acc = correct / total
        scheduler.step(val_acc)

        end_epoch = time.time()
        print(f'Epoch [{epoch+1} / {epochs}]: Train Loss={total_loss:.4f}, Train Acc={train_acc:.4f}, Val Acc={val_acc:.4f}, LR={optimizer.param_groups[0]["lr"]:.4f}, Time={end_epoch - start_epoch:.4f} sec')

        # Early stopping
        if val_acc > best_acc:
            best_acc = val_acc
            best_ckpt = model.state_dict()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print("Early stopping triggered.")
                break

    return model, best_ckpt

### Train AttentionClassifier

In [199]:
train_dataset = ProteinDataset(sequences, labels, label2idx) # Use the lists loaded from train.csv
val_dataset = ProteinDataset(seq_val, label_val, label2idx)  # Use the lists loaded from val.csv
num_classes = len(label_list)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

model = AttentionClassifier(
    num_classes,
    embed_dim=64,
    num_heads=2,
    num_layers=1,
    ff_dim=128,
    dropout_p=0.1
).to(device)

model, best_ckpt = train_model(model, train_dataset, val_dataset, num_classes=num_classes, epochs=100, batch_size=16, lr=5e-3, patience=15, device=device, wd=1e-4)
model.load_state_dict(best_ckpt)

df_test = pd.read_csv('test.csv')
test_sequences = df_test['Sequence'].tolist()
test_seq2name = {seq: f'test_seq_{i}' for i, seq in enumerate(test_sequences)}
test_dataset = ProteinDataset(test_sequences, [label_list[0]]*len(test_sequences), label2idx)
test_loader = DataLoader(test_dataset, batch_size=64, collate_fn=collate_fn)

model.eval()
preds = []
with torch.no_grad():
    for batch_seqs, batch_lens, _ in test_loader:
        ######################################################################
        # TODO: inference on the test set
        batch_seqs, batch_lens = batch_seqs.to(device), batch_lens.to(device)
        outputs = model(batch_seqs, batch_lens)
        preds.extend(torch.argmax(outputs, dim=1).cpu().tolist())
        ######################################################################
# save the predictions to a individual CSV file
preds = [label_list[pred] for pred in preds]
df_preds = pd.DataFrame(preds)
df_preds.to_csv('test_preds_attention.csv', index=False, header=False)

Encoding sequences: 100%|██████████| 18094/18094 [00:02<00:00, 7332.53it/s]
Encoding sequences: 100%|██████████| 3877/3877 [00:00<00:00, 8680.06it/s]

Epoch [1 / 100]: Train Loss=5300.7364, Train Acc=0.0652, Val Acc=0.1034, LR=0.0050, Time=11.3576 sec
Epoch [2 / 100]: Train Loss=4697.7063, Train Acc=0.1615, Val Acc=0.1888, LR=0.0050, Time=11.1555 sec
Epoch [3 / 100]: Train Loss=4320.9661, Train Acc=0.2481, Val Acc=0.2688, LR=0.0050, Time=11.2945 sec
Epoch [4 / 100]: Train Loss=4085.4930, Train Acc=0.2999, Val Acc=0.3283, LR=0.0050, Time=11.2071 sec
Epoch [5 / 100]: Train Loss=3911.1972, Train Acc=0.3351, Val Acc=0.3490, LR=0.0050, Time=11.1071 sec
Epoch [6 / 100]: Train Loss=3762.0151, Train Acc=0.3668, Val Acc=0.3799, LR=0.0050, Time=11.4221 sec
Epoch [7 / 100]: Train Loss=3643.3813, Train Acc=0.3915, Val Acc=0.3949, LR=0.0050, Time=11.3778 sec
Epoch [8 / 100]: Train Loss=3522.4348, Train Acc=0.4190, Val Acc=0.4238, LR=0.0050, Time=11.5112 sec
Epoch [9 / 100]: Train Loss=3420.7105, Train Acc=0.4400, Val Acc=0.4297, LR=0.0050, Time=11.4845 sec
Epoch [10 / 100]: Train Loss=3321.6127, Train Acc=0.4655, Val Acc=0.4573, LR=0.0050, Time=11.3834 sec
Epoch [11 / 100]: Train Loss=3238.4760, Train Acc=0.4833, Val Acc=0.4774, LR=0.0050, Time=11.3090 sec
Epoch [12 / 100]: Train Loss=3179.0590, Train Acc=0.4952, Val Acc=0.4839, LR=0.0050, Time=11.3382 sec
Epoch [13 / 100]: Train Loss=3114.4539, Train Acc=0.5131, Val Acc=0.4849, LR=0.0050, Time=11.4560 sec
Epoch [14 / 100]: Train Loss=3066.2086, Train Acc=0.5221, Val Acc=0.5094, LR=0.0050, Time=10.6901 sec
Epoch [15 / 100]: Train Loss=3010.9600, Train Acc=0.5364, Val Acc=0.4926, LR=0.0050, Time=10.5659 sec
Epoch [16 / 100]: Train Loss=2962.4417, Train Acc=0.5517, Val Acc=0.5272, LR=0.0050, Time=10.6234 sec
Epoch [17 / 100]: Train Loss=2928.8076, Train Acc=0.5539, Val Acc=0.5202, LR=0.0050, Time=10.8245 sec
Epoch [18 / 100]: Train Loss=2889.4420, Train Acc=0.5653, Val Acc=0.5399, LR=0.0050, Time=10.5808 sec
Epoch [19 / 100]: Train Loss=2852.6960, Train Acc=0.5736, Val Acc=0.5357, LR=0.0050, Time=10.6141 sec
Epoch [20 / 100]: Train Loss=2818.1456, Train Acc=0.5812, Val Acc=0.5453, LR=0.0050, Time=10.7198 sec
Epoch [21 / 100]: Train Loss=2786.6501, Train Acc=0.5893, Val Acc=0.5558, LR=0.0050, Time=10.6113 sec
Epoch [22 / 100]: Train Loss=2767.8312, Train Acc=0.5926, Val Acc=0.5600, LR=0.0050, Time=10.6509 sec
Epoch [23 / 100]: Train Loss=2733.5382, Train Acc=0.6058, Val Acc=0.5659, LR=0.0050, Time=11.3329 sec
Epoch [24 / 100]: Train Loss=2714.8497, Train Acc=0.6088, Val Acc=0.5770, LR=0.0050, Time=11.4740 sec
Epoch [25 / 100]: Train Loss=2695.0581, Train Acc=0.6092, Val Acc=0.5860, LR=0.0050, Time=11.5947 sec
Epoch [26 / 100]: Train Loss=2665.1905, Train Acc=0.6236, Val Acc=0.5852, LR=0.0050, Time=10.5667 sec
Epoch [27 / 100]: Train Loss=2647.3531, Train Acc=0.6220, Val Acc=0.5845, LR=0.0050, Time=10.7308 sec
Epoch [28 / 100]: Train Loss=2629.3932, Train Acc=0.6288, Val Acc=0.5734, LR=0.0050, Time=10.6506 sec
Epoch [29 / 100]: Train Loss=2609.1023, Train Acc=0.6367, Val Acc=0.5961, LR=0.0050, Time=11.3527 sec
Epoch [30 / 100]: Train Loss=2595.4906, Train Acc=0.6391, Val Acc=0.5791, LR=0.0050, Time=11.6429 sec
Epoch [31 / 100]: Train Loss=2565.3824, Train Acc=0.6451, Val Acc=0.5883, LR=0.0050, Time=11.6832 sec
Epoch [32 / 100]: Train Loss=2556.1539, Train Acc=0.6474, Val Acc=0.6059, LR=0.0050, Time=11.9032 sec
Epoch [33 / 100]: Train Loss=2552.4205, Train Acc=0.6477, Val Acc=0.5981, LR=0.0050, Time=11.0511 sec
Epoch [34 / 100]: Train Loss=2528.5875, Train Acc=0.6547, Val Acc=0.6121, LR=0.0050, Time=10.8675 sec
Epoch [35 / 100]: Train Loss=2528.0658, Train Acc=0.6560, Val Acc=0.6152, LR=0.0050, Time=10.7736 sec
Epoch [36 / 100]: Train Loss=2514.4790, Train Acc=0.6577, Val Acc=0.5958, LR=0.0050, Time=10.5510 sec
Epoch [37 / 100]: Train Loss=2497.8134, Train Acc=0.6637, Val Acc=0.6121, LR=0.0050, Time=10.9916 sec
Epoch [38 / 100]: Train Loss=2490.7014, Train Acc=0.6649, Val Acc=0.6175, LR=0.0050, Time=10.9177 sec
Epoch [39 / 100]: Train Loss=2479.5436, Train Acc=0.6678, Val Acc=0.6154, LR=0.0050, Time=11.1837 sec
Epoch [40 / 100]: Train Loss=2467.6716, Train Acc=0.6719, Val Acc=0.6108, LR=0.0050, Time=11.5753 sec
Epoch [41 / 100]: Train Loss=2458.6703, Train Acc=0.6738, Val Acc=0.6002, LR=0.0050, Time=11.5423 sec
Epoch [42 / 100]: Train Loss=2452.8296, Train Acc=0.6725, Val Acc=0.6229, LR=0.0050, Time=10.7838 sec
Epoch [43 / 100]: Train Loss=2441.5470, Train Acc=0.6765, Val Acc=0.6232, LR=0.0050, Time=10.7229 sec
Epoch [44 / 100]: Train Loss=2435.6110, Train Acc=0.6796, Val Acc=0.6188, LR=0.0050, Time=10.6874 sec
Epoch [45 / 100]: Train Loss=2427.9073, Train Acc=0.6823, Val Acc=0.6201, LR=0.0050, Time=10.8948 sec
Epoch [46 / 100]: Train Loss=2421.6258, Train Acc=0.6854, Val Acc=0.6255, LR=0.0050, Time=10.7222 sec
Epoch [47 / 100]: Train Loss=2406.1738, Train Acc=0.6868, Val Acc=0.6299, LR=0.0050, Time=10.9823 sec
Epoch [48 / 100]: Train Loss=2400.5145, Train Acc=0.6902, Val Acc=0.6159, LR=0.0050, Time=10.7496 sec
Epoch [49 / 100]: Train Loss=2402.7241, Train Acc=0.6851, Val Acc=0.6433, LR=0.0050, Time=10.6349 sec
Epoch [50 / 100]: Train Loss=2382.3588, Train Acc=0.6923, Val Acc=0.6392, LR=0.0050, Time=10.9499 sec
Epoch [51 / 100]: Train Loss=2385.4549, Train Acc=0.6909, Val Acc=0.6469, LR=0.0050, Time=10.4484 sec
Epoch [52 / 100]: Train Loss=2377.1758, Train Acc=0.6947, Val Acc=0.6252, LR=0.0050, Time=10.8241 sec
Epoch [53 / 100]: Train Loss=2374.0750, Train Acc=0.6929, Val Acc=0.6448, LR=0.0050, Time=10.6643 sec
Epoch [54 / 100]: Train Loss=2362.8555, Train Acc=0.6960, Val Acc=0.6448, LR=0.0050, Time=10.9581 sec
Epoch [55 / 100]: Train Loss=2362.2431, Train Acc=0.6979, Val Acc=0.6446, LR=0.0050, Time=10.6335 sec
Epoch [56 / 100]: Train Loss=2355.2234, Train Acc=0.7003, Val Acc=0.6113, LR=0.0025, Time=11.0194 sec
Epoch [57 / 100]: Train Loss=2177.6075, Train Acc=0.7482, Val Acc=0.6624, LR=0.0025, Time=10.6501 sec
Epoch [58 / 100]: Train Loss=2147.1919, Train Acc=0.7571, Val Acc=0.6742, LR=0.0025, Time=10.3285 sec
Epoch [59 / 100]: Train Loss=2135.9617, Train Acc=0.7584, Val Acc=0.6742, LR=0.0025, Time=10.9724 sec
Epoch [60 / 100]: Train Loss=2136.3871, Train Acc=0.7600, Val Acc=0.6662, LR=0.0025, Time=10.6502 sec
Epoch [61 / 100]: Train Loss=2131.5992, Train Acc=0.7617, Val Acc=0.6665, LR=0.0025, Time=10.8005 sec
Epoch [62 / 100]: Train Loss=2121.9206, Train Acc=0.7647, Val Acc=0.6683, LR=0.0025, Time=11.0753 sec
Epoch [63 / 100]: Train Loss=2119.2515, Train Acc=0.7642, Val Acc=0.6619, LR=0.0013, Time=10.6168 sec
Epoch [64 / 100]: Train Loss=2028.4787, Train Acc=0.7885, Val Acc=0.6858, LR=0.0013, Time=11.1937 sec
Epoch [65 / 100]: Train Loss=2015.0572, Train Acc=0.7964, Val Acc=0.6827, LR=0.0013, Time=11.3796 sec
Epoch [66 / 100]: Train Loss=2006.4003, Train Acc=0.7983, Val Acc=0.6799, LR=0.0013, Time=11.4267 sec
Epoch [67 / 100]: Train Loss=2004.6941, Train Acc=0.7977, Val Acc=0.6858, LR=0.0013, Time=11.4379 sec
Epoch [68 / 100]: Train Loss=2000.5876, Train Acc=0.7998, Val Acc=0.6812, LR=0.0013, Time=11.4139 sec
Epoch [69 / 100]: Train Loss=1998.8654, Train Acc=0.8009, Val Acc=0.6910, LR=0.0013, Time=11.6307 sec
Epoch [70 / 100]: Train Loss=1993.8151, Train Acc=0.8015, Val Acc=0.6840, LR=0.0013, Time=11.6383 sec
Epoch [71 / 100]: Train Loss=1988.5391, Train Acc=0.8023, Val Acc=0.6807, LR=0.0013, Time=11.5751 sec
Epoch [72 / 100]: Train Loss=1984.9852, Train Acc=0.8042, Val Acc=0.6822, LR=0.0013, Time=11.2564 sec
Epoch [73 / 100]: Train Loss=1983.0262, Train Acc=0.8061, Val Acc=0.6835, LR=0.0013, Time=11.3075 sec
Epoch [74 / 100]: Train Loss=1984.8109, Train Acc=0.8035, Val Acc=0.6905, LR=0.0006, Time=11.5727 sec
Epoch [75 / 100]: Train Loss=1937.6674, Train Acc=0.8196, Val Acc=0.6949, LR=0.0006, Time=11.6627 sec
Epoch [76 / 100]: Train Loss=1930.4119, Train Acc=0.8219, Val Acc=0.6951, LR=0.0006, Time=11.4516 sec
Epoch [77 / 100]: Train Loss=1925.0866, Train Acc=0.8219, Val Acc=0.6974, LR=0.0006, Time=11.4354 sec
Epoch [78 / 100]: Train Loss=1923.2299, Train Acc=0.8251, Val Acc=0.6990, LR=0.0006, Time=11.5067 sec
Epoch [79 / 100]: Train Loss=1923.9736, Train Acc=0.8215, Val Acc=0.6925, LR=0.0006, Time=11.4293 sec
Epoch [80 / 100]: Train Loss=1923.2457, Train Acc=0.8244, Val Acc=0.6928, LR=0.0006, Time=11.5026 sec
Epoch [81 / 100]: Train Loss=1916.2191, Train Acc=0.8213, Val Acc=0.6949, LR=0.0006, Time=11.5338 sec
Epoch [82 / 100]: Train Loss=1917.4908, Train Acc=0.8265, Val Acc=0.6987, LR=0.0006, Time=11.3859 sec
Epoch [83 / 100]: Train Loss=1917.5917, Train Acc=0.8268, Val Acc=0.6910, LR=0.0003, Time=11.4286 sec
Epoch [84 / 100]: Train Loss=1891.4049, Train Acc=0.8342, Val Acc=0.6931, LR=0.0003, Time=11.4998 sec
Epoch [85 / 100]: Train Loss=1884.4466, Train Acc=0.8357, Val Acc=0.6990, LR=0.0003, Time=11.4289 sec
Epoch [86 / 100]: Train Loss=1884.0094, Train Acc=0.8331, Val Acc=0.6969, LR=0.0003, Time=11.4032 sec
Epoch [87 / 100]: Train Loss=1883.9327, Train Acc=0.8352, Val Acc=0.6987, LR=0.0003, Time=11.4181 sec
Epoch [88 / 100]: Train Loss=1879.5526, Train Acc=0.8359, Val Acc=0.7005, LR=0.0003, Time=11.4356 sec
Epoch [89 / 100]: Train Loss=1883.3850, Train Acc=0.8344, Val Acc=0.7018, LR=0.0003, Time=11.4759 sec
Epoch [90 / 100]: Train Loss=1882.1494, Train Acc=0.8350, Val Acc=0.6987, LR=0.0003, Time=11.4529 sec
Epoch [91 / 100]: Train Loss=1876.7350, Train Acc=0.8376, Val Acc=0.6993, LR=0.0003, Time=11.5417 sec
Epoch [92 / 100]: Train Loss=1877.1171, Train Acc=0.8376, Val Acc=0.7000, LR=0.0003, Time=11.4399 sec
Epoch [93 / 100]: Train Loss=1879.5915, Train Acc=0.8375, Val Acc=0.7000, LR=0.0003, Time=11.4734 sec
Epoch [94 / 100]: Train Loss=1880.3139, Train Acc=0.8364, Val Acc=0.7013, LR=0.0002, Time=11.4296 sec
Epoch [95 / 100]: Train Loss=1863.8783, Train Acc=0.8432, Val Acc=0.6990, LR=0.0002, Time=11.4709 sec
Epoch [96 / 100]: Train Loss=1864.1198, Train Acc=0.8401, Val Acc=0.6998, LR=0.0002, Time=11.6632 sec
Epoch [97 / 100]: Train Loss=1860.3510, Train Acc=0.8405, Val Acc=0.7011, LR=0.0002, Time=11.4332 sec
Epoch [98 / 100]: Train Loss=1859.9162, Train Acc=0.8446, Val Acc=0.7013, LR=0.0002, Time=11.5152 sec
Epoch [99 / 100]: Train Loss=1858.3483, Train Acc=0.8431, Val Acc=0.7026, LR=0.0002, Time=11.6851 sec
Epoch [100 / 100]: Train Loss=1859.1900, Train Acc=0.8433, Val Acc=0.7047, LR=0.0002, Time=11.0845 sec

Encoding sequences: 100%|██████████| 3878/3878 [00:00<00:00, 5843.58it/s]

In [200]:
'''
Best trials:  
Trial 21 finished with value: 0.46762961052360075 and parameters: {'learning_rate': 0.004550336419726336, 'num_heads': 1, 'num_layers': 2, 'dropout_p': 0.10328973400525898, 'wd': 0.027927639305451207}
Trial 26 finished with value: 0.47175651276760383 and parameters: {'learning_rate': 0.005088370821326657, 'num_heads': 1, 'num_layers': 2, 'dropout_p': 0.10106683010377945, 'wd': 0.013552521785811001}
'''
# print(study.best_trial.params)

"\nBest trials:  \nTrial 21 finished with value: 0.46762961052360075 and parameters: {'learning_rate': 0.004550336419726336, 'num_heads': 1, 'num_layers': 2, 'dropout_p': 0.10328973400525898, 'wd': 0.027927639305451207}\nTrial 26 finished with value: 0.47175651276760383 and parameters: {'learning_rate': 0.005088370821326657, 'num_heads': 1, 'num_layers': 2, 'dropout_p': 0.10106683010377945, 'wd': 0.013552521785811001}\n"

### Train TransformerClassifier

In [201]:
model = TransformerClassifier(num_classes,
                embed_dim=64,
                num_heads=2,
                num_layers=1,
                ff_dim=128,
                dropout_p=0.1).to(device)
model, best_ckpt = train_model(model, train_dataset, val_dataset, num_classes=num_classes, epochs=120, batch_size=30, lr=5e-3, patience=15, device=device, wd=1e-4)
model.load_state_dict(best_ckpt)

model.eval()
preds = []
with torch.no_grad():
    for batch_seqs, batch_lens, _ in test_loader:
        ######################################################################
        # TODO: inference on the test set
        batch_seqs, batch_lens = batch_seqs.to(device), batch_lens.to(device)
        outputs = model(batch_seqs, batch_lens)
        preds.extend(torch.argmax(outputs, dim=1).cpu().tolist())
        ######################################################################

preds = [label_list[pred] for pred in preds]
df_preds = pd.DataFrame(preds)
df_preds.to_csv('test_preds_transformer.csv', index=False, header=False)

Epoch [1 / 120]: Train Loss=2829.9706, Train Acc=0.0666, Val Acc=0.1060, LR=0.0050, Time=8.9753 sec
Epoch [2 / 120]: Train Loss=2547.3009, Train Acc=0.1591, Val Acc=0.2017, LR=0.0050, Time=9.0760 sec
Epoch [3 / 120]: Train Loss=2311.5083, Train Acc=0.2502, Val Acc=0.2824, LR=0.0050, Time=9.0919 sec
Epoch [4 / 120]: Train Loss=2126.0736, Train Acc=0.3245, Val Acc=0.3474, LR=0.0050, Time=9.1242 sec
Epoch [5 / 120]: Train Loss=1989.8681, Train Acc=0.3806, Val Acc=0.3959, LR=0.0050, Time=9.0610 sec
Epoch [6 / 120]: Train Loss=1877.8649, Train Acc=0.4348, Val Acc=0.4256, LR=0.0050, Time=9.1381 sec
Epoch [7 / 120]: Train Loss=1785.5960, Train Acc=0.4713, Val Acc=0.4403, LR=0.0050, Time=9.1405 sec
Epoch [8 / 120]: Train Loss=1718.0780, Train Acc=0.5020, Val Acc=0.4712, LR=0.0050, Time=9.1364 sec
Epoch [9 / 120]: Train Loss=1655.0864, Train Acc=0.5287, Val Acc=0.5022, LR=0.0050, Time=9.2119 sec
Epoch [10 / 120]: Train Loss=1605.9725, Train Acc=0.5486, Val Acc=0.5267, LR=0.0050, Time=9.2514 sec
Epoch [11 / 120]: Train Loss=1557.9297, Train Acc=0.5712, Val Acc=0.5192, LR=0.0050, Time=9.1658 sec
Epoch [12 / 120]: Train Loss=1519.4919, Train Acc=0.5868, Val Acc=0.5169, LR=0.0050, Time=9.1807 sec
Epoch [13 / 120]: Train Loss=1486.9212, Train Acc=0.6020, Val Acc=0.5463, LR=0.0050, Time=9.0594 sec
Epoch [14 / 120]: Train Loss=1461.5787, Train Acc=0.6147, Val Acc=0.5607, LR=0.0050, Time=8.9337 sec
Epoch [15 / 120]: Train Loss=1438.1246, Train Acc=0.6216, Val Acc=0.5690, LR=0.0050, Time=9.0553 sec
Epoch [16 / 120]: Train Loss=1415.9336, Train Acc=0.6346, Val Acc=0.5551, LR=0.0050, Time=8.6713 sec
Epoch [17 / 120]: Train Loss=1389.8856, Train Acc=0.6403, Val Acc=0.5638, LR=0.0050, Time=8.8504 sec
Epoch [18 / 120]: Train Loss=1374.4213, Train Acc=0.6516, Val Acc=0.5845, LR=0.0050, Time=8.8560 sec
Epoch [19 / 120]: Train Loss=1352.5879, Train Acc=0.6614, Val Acc=0.5822, LR=0.0050, Time=8.8260 sec
Epoch [20 / 120]: Train Loss=1339.1009, Train Acc=0.6661, Val Acc=0.5592, LR=0.0050, Time=8.7192 sec
Epoch [21 / 120]: Train Loss=1322.5823, Train Acc=0.6736, Val Acc=0.5803, LR=0.0050, Time=8.7809 sec
Epoch [22 / 120]: Train Loss=1310.8085, Train Acc=0.6808, Val Acc=0.5997, LR=0.0050, Time=8.7613 sec
Epoch [23 / 120]: Train Loss=1298.3308, Train Acc=0.6867, Val Acc=0.6043, LR=0.0050, Time=8.8213 sec
Epoch [24 / 120]: Train Loss=1289.7353, Train Acc=0.6901, Val Acc=0.6128, LR=0.0050, Time=8.8083 sec
Epoch [25 / 120]: Train Loss=1273.4745, Train Acc=0.7002, Val Acc=0.6092, LR=0.0050, Time=8.7819 sec
Epoch [26 / 120]: Train Loss=1262.0505, Train Acc=0.7050, Val Acc=0.6041, LR=0.0050, Time=8.8984 sec
Epoch [27 / 120]: Train Loss=1250.9881, Train Acc=0.7119, Val Acc=0.6085, LR=0.0050, Time=8.9921 sec
Epoch [28 / 120]: Train Loss=1242.0987, Train Acc=0.7154, Val Acc=0.6175, LR=0.0050, Time=8.8879 sec
Epoch [29 / 120]: Train Loss=1234.7110, Train Acc=0.7190, Val Acc=0.6123, LR=0.0050, Time=8.7901 sec
Epoch [30 / 120]: Train Loss=1230.8613, Train Acc=0.7180, Val Acc=0.6214, LR=0.0050, Time=9.0419 sec
Epoch [31 / 120]: Train Loss=1220.6206, Train Acc=0.7269, Val Acc=0.6232, LR=0.0050, Time=8.8188 sec
Epoch [32 / 120]: Train Loss=1216.0707, Train Acc=0.7283, Val Acc=0.6211, LR=0.0050, Time=8.6809 sec
Epoch [33 / 120]: Train Loss=1204.7922, Train Acc=0.7312, Val Acc=0.6273, LR=0.0050, Time=8.9461 sec
Epoch [34 / 120]: Train Loss=1204.3347, Train Acc=0.7313, Val Acc=0.6126, LR=0.0050, Time=8.8635 sec
Epoch [35 / 120]: Train Loss=1195.1002, Train Acc=0.7385, Val Acc=0.6306, LR=0.0050, Time=8.8079 sec
Epoch [36 / 120]: Train Loss=1191.9133, Train Acc=0.7365, Val Acc=0.6324, LR=0.0050, Time=8.8449 sec
Epoch [37 / 120]: Train Loss=1181.9270, Train Acc=0.7422, Val Acc=0.6157, LR=0.0050, Time=8.9539 sec
Epoch [38 / 120]: Train Loss=1180.2891, Train Acc=0.7468, Val Acc=0.6294, LR=0.0050, Time=8.8481 sec
Epoch [39 / 120]: Train Loss=1176.1860, Train Acc=0.7449, Val Acc=0.6234, LR=0.0050, Time=8.7183 sec
Epoch [40 / 120]: Train Loss=1165.8391, Train Acc=0.7491, Val Acc=0.6306, LR=0.0050, Time=8.9942 sec
Epoch [41 / 120]: Train Loss=1166.9750, Train Acc=0.7510, Val Acc=0.6373, LR=0.0050, Time=8.9037 sec
Epoch [42 / 120]: Train Loss=1162.8438, Train Acc=0.7515, Val Acc=0.6422, LR=0.0050, Time=8.8087 sec
Epoch [43 / 120]: Train Loss=1156.4921, Train Acc=0.7559, Val Acc=0.6348, LR=0.0050, Time=8.6723 sec
Epoch [44 / 120]: Train Loss=1152.5759, Train Acc=0.7585, Val Acc=0.6345, LR=0.0050, Time=8.6955 sec
Epoch [45 / 120]: Train Loss=1150.1779, Train Acc=0.7571, Val Acc=0.6317, LR=0.0050, Time=8.6675 sec
Epoch [46 / 120]: Train Loss=1144.8989, Train Acc=0.7595, Val Acc=0.6257, LR=0.0050, Time=8.7779 sec
Epoch [47 / 120]: Train Loss=1139.8028, Train Acc=0.7640, Val Acc=0.6443, LR=0.0050, Time=8.7163 sec
Epoch [48 / 120]: Train Loss=1136.0212, Train Acc=0.7645, Val Acc=0.6482, LR=0.0050, Time=8.7727 sec
Epoch [49 / 120]: Train Loss=1135.4202, Train Acc=0.7644, Val Acc=0.6358, LR=0.0050, Time=8.7292 sec
Epoch [50 / 120]: Train Loss=1129.4031, Train Acc=0.7677, Val Acc=0.6466, LR=0.0050, Time=8.7922 sec
Epoch [51 / 120]: Train Loss=1126.4912, Train Acc=0.7699, Val Acc=0.6412, LR=0.0050, Time=8.9188 sec
Epoch [52 / 120]: Train Loss=1126.5789, Train Acc=0.7663, Val Acc=0.6412, LR=0.0050, Time=8.8406 sec
Epoch [53 / 120]: Train Loss=1120.0125, Train Acc=0.7727, Val Acc=0.6392, LR=0.0025, Time=8.7045 sec
Epoch [54 / 120]: Train Loss=1039.8762, Train Acc=0.8170, Val Acc=0.6662, LR=0.0025, Time=8.8100 sec
Epoch [55 / 120]: Train Loss=1027.1134, Train Acc=0.8262, Val Acc=0.6616, LR=0.0025, Time=9.0665 sec
Epoch [56 / 120]: Train Loss=1023.1247, Train Acc=0.8270, Val Acc=0.6580, LR=0.0025, Time=8.9225 sec
Epoch [57 / 120]: Train Loss=1019.0713, Train Acc=0.8280, Val Acc=0.6652, LR=0.0025, Time=8.9157 sec
Epoch [58 / 120]: Train Loss=1016.7142, Train Acc=0.8326, Val Acc=0.6665, LR=0.0025, Time=8.7258 sec
Epoch [59 / 120]: Train Loss=1011.9534, Train Acc=0.8316, Val Acc=0.6611, LR=0.0025, Time=9.0130 sec
Epoch [60 / 120]: Train Loss=1010.8110, Train Acc=0.8344, Val Acc=0.6598, LR=0.0025, Time=8.9987 sec
Epoch [61 / 120]: Train Loss=1006.8382, Train Acc=0.8382, Val Acc=0.6595, LR=0.0025, Time=8.8063 sec
Epoch [62 / 120]: Train Loss=1005.7921, Train Acc=0.8356, Val Acc=0.6665, LR=0.0025, Time=8.8445 sec
Epoch [63 / 120]: Train Loss=1004.9165, Train Acc=0.8356, Val Acc=0.6642, LR=0.0013, Time=8.8555 sec
Epoch [64 / 120]: Train Loss=962.9312, Train Acc=0.8635, Val Acc=0.6688, LR=0.0013, Time=8.9380 sec
Epoch [65 / 120]: Train Loss=955.7492, Train Acc=0.8666, Val Acc=0.6688, LR=0.0013, Time=8.7083 sec
Epoch [66 / 120]: Train Loss=954.3405, Train Acc=0.8682, Val Acc=0.6758, LR=0.0013, Time=8.9041 sec
Epoch [67 / 120]: Train Loss=952.2967, Train Acc=0.8686, Val Acc=0.6745, LR=0.0013, Time=8.8418 sec
Epoch [68 / 120]: Train Loss=951.0580, Train Acc=0.8702, Val Acc=0.6688, LR=0.0013, Time=8.8839 sec
Epoch [69 / 120]: Train Loss=947.9317, Train Acc=0.8717, Val Acc=0.6675, LR=0.0013, Time=8.9055 sec
Epoch [70 / 120]: Train Loss=947.6110, Train Acc=0.8722, Val Acc=0.6727, LR=0.0013, Time=8.8391 sec
Epoch [71 / 120]: Train Loss=948.1453, Train Acc=0.8716, Val Acc=0.6735, LR=0.0006, Time=8.9402 sec
Epoch [72 / 120]: Train Loss=924.5365, Train Acc=0.8871, Val Acc=0.6760, LR=0.0006, Time=8.9720 sec
Epoch [73 / 120]: Train Loss=921.0622, Train Acc=0.8877, Val Acc=0.6729, LR=0.0006, Time=8.8863 sec
Epoch [74 / 120]: Train Loss=920.4889, Train Acc=0.8883, Val Acc=0.6719, LR=0.0006, Time=8.9638 sec
Epoch [75 / 120]: Train Loss=920.4105, Train Acc=0.8885, Val Acc=0.6737, LR=0.0006, Time=8.8792 sec
Epoch [76 / 120]: Train Loss=920.0285, Train Acc=0.8891, Val Acc=0.6760, LR=0.0006, Time=8.8876 sec
Epoch [77 / 120]: Train Loss=917.8146, Train Acc=0.8922, Val Acc=0.6740, LR=0.0003, Time=8.9191 sec
Epoch [78 / 120]: Train Loss=906.0416, Train Acc=0.8975, Val Acc=0.6750, LR=0.0003, Time=8.8762 sec
Epoch [79 / 120]: Train Loss=903.9687, Train Acc=0.9011, Val Acc=0.6742, LR=0.0003, Time=8.8588 sec
Epoch [80 / 120]: Train Loss=903.9077, Train Acc=0.9022, Val Acc=0.6737, LR=0.0003, Time=8.9087 sec
Epoch [81 / 120]: Train Loss=902.0649, Train Acc=0.9013, Val Acc=0.6719, LR=0.0003, Time=8.8946 sec
Epoch [82 / 120]: Train Loss=902.8230, Train Acc=0.9018, Val Acc=0.6750, LR=0.0002, Time=8.9209 sec
Epoch [83 / 120]: Train Loss=898.2285, Train Acc=0.9048, Val Acc=0.6747, LR=0.0002, Time=8.8999 sec
Epoch [84 / 120]: Train Loss=896.6732, Train Acc=0.9057, Val Acc=0.6771, LR=0.0002, Time=8.9072 sec
Epoch [85 / 120]: Train Loss=895.6712, Train Acc=0.9058, Val Acc=0.6755, LR=0.0002, Time=8.8769 sec
Epoch [86 / 120]: Train Loss=894.7066, Train Acc=0.9049, Val Acc=0.6781, LR=0.0002, Time=8.9880 sec
Epoch [87 / 120]: Train Loss=894.0103, Train Acc=0.9060, Val Acc=0.6776, LR=0.0002, Time=8.9441 sec
Epoch [88 / 120]: Train Loss=894.5682, Train Acc=0.9068, Val Acc=0.6760, LR=0.0002, Time=9.0582 sec
Epoch [89 / 120]: Train Loss=893.9416, Train Acc=0.9070, Val Acc=0.6763, LR=0.0002, Time=8.9838 sec
Epoch [90 / 120]: Train Loss=895.4764, Train Acc=0.9058, Val Acc=0.6776, LR=0.0002, Time=9.2711 sec
Epoch [91 / 120]: Train Loss=892.9786, Train Acc=0.9079, Val Acc=0.6784, LR=0.0002, Time=9.1587 sec
Epoch [92 / 120]: Train Loss=893.2089, Train Acc=0.9060, Val Acc=0.6781, LR=0.0002, Time=9.1496 sec
Epoch [93 / 120]: Train Loss=892.9751, Train Acc=0.9063, Val Acc=0.6760, LR=0.0002, Time=9.1024 sec
Epoch [94 / 120]: Train Loss=892.5807, Train Acc=0.9082, Val Acc=0.6786, LR=0.0002, Time=9.2047 sec
Epoch [95 / 120]: Train Loss=893.1584, Train Acc=0.9089, Val Acc=0.6768, LR=0.0002, Time=9.2410 sec
Epoch [96 / 120]: Train Loss=892.8083, Train Acc=0.9089, Val Acc=0.6776, LR=0.0002, Time=8.8464 sec
Epoch [97 / 120]: Train Loss=892.3226, Train Acc=0.9081, Val Acc=0.6786, LR=0.0002, Time=8.9241 sec
Epoch [98 / 120]: Train Loss=892.2652, Train Acc=0.9079, Val Acc=0.6766, LR=0.0002, Time=8.8714 sec
Epoch [99 / 120]: Train Loss=892.0735, Train Acc=0.9079, Val Acc=0.6760, LR=0.0001, Time=8.8923 sec
Epoch [100 / 120]: Train Loss=888.9089, Train Acc=0.9081, Val Acc=0.6768, LR=0.0001, Time=8.8802 sec
Epoch [101 / 120]: Train Loss=888.7541, Train Acc=0.9094, Val Acc=0.6771, LR=0.0001, Time=8.8512 sec
Epoch [102 / 120]: Train Loss=887.7213, Train Acc=0.9112, Val Acc=0.6776, LR=0.0001, Time=8.8837 sec
Epoch [103 / 120]: Train Loss=888.1743, Train Acc=0.9106, Val Acc=0.6778, LR=0.0001, Time=8.9373 sec
Epoch [104 / 120]: Train Loss=886.9665, Train Acc=0.9114, Val Acc=0.6768, LR=0.0000, Time=8.9271 sec
Epoch [105 / 120]: Train Loss=885.4825, Train Acc=0.9127, Val Acc=0.6778, LR=0.0000, Time=8.9340 sec
Epoch [106 / 120]: Train Loss=886.0749, Train Acc=0.9110, Val Acc=0.6778, LR=0.0000, Time=8.8791 sec
Epoch [107 / 120]: Train Loss=886.3460, Train Acc=0.9127, Val Acc=0.6763, LR=0.0000, Time=8.8296 sec
Epoch [108 / 120]: Train Loss=885.5163, Train Acc=0.9115, Val Acc=0.6773, LR=0.0000, Time=8.9933 sec
Epoch [109 / 120]: Train Loss=885.8301, Train Acc=0.9117, Val Acc=0.6778, LR=0.0000, Time=8.8941 sec
Early stopping triggered.

In [133]:
# def objective_transformer(trial):
#     torch.cuda.empty_cache() # Keep mem usage low

#     batch_size = 30
#     learning_rate = trial.suggest_float("learning_rate", 1e-4, 1e-1, log=True)
#     # embed_dim = trial.suggest_int("embed_dim", 64, 128, step=16)
#     num_heads = trial.suggest_int("num_heads", 1, 2, step=1)
#     num_layers = trial.suggest_int("num_layers", 1, 2, step=1)
#     # ff_dim = trial.suggest_int("ff_dim", 128, 256, step=32)
#     dropout_p = trial.suggest_float("dropout_p", 0.1, 0.5)
#     wd = trial.suggest_float("wd", 0.01, 0.1) # Weight decay for AdamW
    
#     model = TransformerClassifier(num_classes,
#                 embed_dim=64,
#                 num_heads=num_heads,
#                 num_layers=num_layers,
#                 ff_dim=128).to(device),
#                 dropout_p=dropout_p
#     model, best_ckpt = train_model(model, train_dataset, val_dataset, num_classes=num_classes, epochs=100, batch_size=batch_size, lr=learning_rate, patience=7, device=device)
#     model.load_state_dict(best_ckpt)
    
#     # Evaluate on validation set to get the metric
#     model.load_state_dict(best_ckpt)
#     model.eval()
#     correct, total = 0, 0
#     val_loader = DataLoader(val_dataset, batch_size=64, collate_fn=collate_fn)
#     with torch.no_grad():
#         for seqs, lens, labels in val_loader:
#             seqs, lens, labels = seqs.to(device), lens.to(device), labels.to(device)
#             outputs = model(seqs, lens)
#             correct += (outputs.argmax(1) == labels).sum().item()
#             total += labels.size(0)
#     val_acc = correct / total
#     return val_acc  # maximize this

# study = optuna.create_study(
#     direction="maximize",
#     pruner=optuna.pruners.MedianPruner(n_startup_trials=3, n_warmup_steps=2))
# study.optimize(objective_attn, n_trials=10)



# model = TransformerClassifier(num_classes,
#                 embed_dim=64,
#                 num_heads=1,
#                 num_layers=1,
#                 ff_dim=128).to(device)
# model, best_ckpt = train_model(model, train_dataset, val_dataset, num_classes=num_classes, epochs=100, batch_size=64, lr=1e-3, patience=7, device=device)
# model.load_state_dict(best_ckpt)

# model.eval()
# preds = []
# with torch.no_grad():
#     for batch_seqs, batch_lens, _ in test_loader:
#         ######################################################################
#         # TODO: inference on the test set
#         batch_seqs, batch_lens = batch_seqs.to(device), batch_lens.to(device)
#         outputs = model(batch_seqs, batch_lens)
#         preds.extend(torch.argmax(outputs, dim=1).cpu().tolist())
#         ######################################################################

# preds = [label_list[pred] for pred in preds]
# df_preds = pd.DataFrame(preds)
# df_preds.to_csv('test_preds_transformer.csv', index=False, header=False)

### Train CNNClassifier

In [ ]:
model = CNNClassifier(num_classes,
            embed_dim=64,
            num_filters=128,
            kernel_size=3,
            num_layers=3).to(device)
model, best_ckpt = train_model(model, train_dataset, val_dataset, num_classes=num_classes, epochs=100, batch_size=64, lr=1e-3, patience=7, device=device)
model.load_state_dict(best_ckpt)

model.eval()
preds = []
with torch.no_grad():
    for batch_seqs, batch_lens, _ in test_loader:
        ######################################################################
        # TODO: inference on the test set
        batch_seqs, batch_lens = batch_seqs.to(device), batch_lens.to(device)
        outputs = model(batch_seqs, batch_lens)
        preds.extend(torch.argmax(outputs, dim=1).cpu().tolist())
        ######################################################################
# save the predictions to a individual CSV file
preds = [label_list[pred] for pred in preds]
df_preds = pd.DataFrame(preds)
df_preds.to_csv('test_preds_cnn.csv', index=False, header=False)

Epoch [1 / 100]: Train Loss=1457.4141, Train Acc=0.0077, Val Acc=0.0142, Time=3.5675 sec
Epoch [2 / 100]: Train Loss=1406.8795, Train Acc=0.0146, Val Acc=0.0155, Time=3.3706 sec
Epoch [3 / 100]: Train Loss=1362.4697, Train Acc=0.0304, Val Acc=0.0426, Time=3.3705 sec
Epoch [4 / 100]: Train Loss=1320.0871, Train Acc=0.0437, Val Acc=0.0536, Time=3.3750 sec
Epoch [5 / 100]: Train Loss=1305.6066, Train Acc=0.0475, Val Acc=0.0500, Time=3.4049 sec
Epoch [6 / 100]: Train Loss=1296.4492, Train Acc=0.0558, Val Acc=0.0562, Time=3.3668 sec
Epoch [7 / 100]: Train Loss=1277.2232, Train Acc=0.0694, Val Acc=0.0702, Time=3.4056 sec
Epoch [8 / 100]: Train Loss=1264.9611, Train Acc=0.0766, Val Acc=0.0838, Time=3.4001 sec
Epoch [9 / 100]: Train Loss=1256.9035, Train Acc=0.0802, Val Acc=0.0800, Time=3.4389 sec
Epoch [10 / 100]: Train Loss=1250.5169, Train Acc=0.0850, Val Acc=0.0776, Time=3.3559 sec
Epoch [11 / 100]: Train Loss=1242.5940, Train Acc=0.0905, Val Acc=0.0898, Time=3.4526 sec
Epoch [12 / 100]: Train Loss=1237.2556, Train Acc=0.0958, Val Acc=0.0923, Time=3.4114 sec
Epoch [13 / 100]: Train Loss=1220.6049, Train Acc=0.1110, Val Acc=0.1140, Time=3.3795 sec
Epoch [14 / 100]: Train Loss=1184.5490, Train Acc=0.1342, Val Acc=0.1372, Time=3.3530 sec
Epoch [15 / 100]: Train Loss=1144.7872, Train Acc=0.1604, Val Acc=0.1713, Time=3.3542 sec
Epoch [16 / 100]: Train Loss=1114.6496, Train Acc=0.1834, Val Acc=0.1800, Time=3.3475 sec
Epoch [17 / 100]: Train Loss=1089.2865, Train Acc=0.2017, Val Acc=0.2007, Time=3.3413 sec
Epoch [18 / 100]: Train Loss=1065.6698, Train Acc=0.2211, Val Acc=0.2316, Time=3.3329 sec
Epoch [19 / 100]: Train Loss=1045.8552, Train Acc=0.2419, Val Acc=0.2234, Time=3.3754 sec
Epoch [20 / 100]: Train Loss=1026.8309, Train Acc=0.2552, Val Acc=0.2435, Time=3.3313 sec
Epoch [21 / 100]: Train Loss=1008.1965, Train Acc=0.2683, Val Acc=0.2781, Time=3.3585 sec
Epoch [22 / 100]: Train Loss=987.3888, Train Acc=0.2865, Val Acc=0.2706, Time=3.3834 sec
Epoch [23 / 100]: Train Loss=968.7380, Train Acc=0.3014, Val Acc=0.2850, Time=3.3617 sec
Epoch [24 / 100]: Train Loss=947.6936, Train Acc=0.3163, Val Acc=0.3036, Time=3.3324 sec
Epoch [25 / 100]: Train Loss=927.0661, Train Acc=0.3307, Val Acc=0.3183, Time=3.3355 sec
Epoch [26 / 100]: Train Loss=908.3212, Train Acc=0.3450, Val Acc=0.3245, Time=3.3791 sec
Epoch [27 / 100]: Train Loss=891.2352, Train Acc=0.3544, Val Acc=0.3351, Time=3.3656 sec
Epoch [28 / 100]: Train Loss=871.4908, Train Acc=0.3717, Val Acc=0.3474, Time=3.3922 sec
Epoch [29 / 100]: Train Loss=856.2032, Train Acc=0.3800, Val Acc=0.3523, Time=3.3575 sec
Epoch [30 / 100]: Train Loss=839.3596, Train Acc=0.3920, Val Acc=0.3665, Time=3.3430 sec
Epoch [31 / 100]: Train Loss=822.4157, Train Acc=0.4013, Val Acc=0.3701, Time=3.3435 sec
Epoch [32 / 100]: Train Loss=804.8446, Train Acc=0.4116, Val Acc=0.3846, Time=3.3331 sec
Epoch [33 / 100]: Train Loss=791.1648, Train Acc=0.4223, Val Acc=0.3918, Time=3.3206 sec
Epoch [34 / 100]: Train Loss=779.3965, Train Acc=0.4295, Val Acc=0.3977, Time=3.3205 sec
Epoch [35 / 100]: Train Loss=765.0513, Train Acc=0.4402, Val Acc=0.4127, Time=3.3330 sec
Epoch [36 / 100]: Train Loss=752.2654, Train Acc=0.4465, Val Acc=0.4127, Time=3.3430 sec
Epoch [37 / 100]: Train Loss=739.8489, Train Acc=0.4573, Val Acc=0.4171, Time=3.3932 sec
Epoch [38 / 100]: Train Loss=728.6391, Train Acc=0.4639, Val Acc=0.4225, Time=3.3469 sec
Epoch [39 / 100]: Train Loss=718.2199, Train Acc=0.4759, Val Acc=0.4382, Time=3.3472 sec
Epoch [40 / 100]: Train Loss=709.0197, Train Acc=0.4731, Val Acc=0.4362, Time=3.3082 sec
Epoch [41 / 100]: Train Loss=696.6461, Train Acc=0.4871, Val Acc=0.4460, Time=3.3038 sec
Epoch [42 / 100]: Train Loss=688.0990, Train Acc=0.4932, Val Acc=0.4393, Time=3.3106 sec
Epoch [43 / 100]: Train Loss=677.8699, Train Acc=0.4976, Val Acc=0.4607, Time=3.2716 sec
Epoch [44 / 100]: Train Loss=668.6911, Train Acc=0.5044, Val Acc=0.4534, Time=3.3306 sec
Epoch [45 / 100]: Train Loss=658.5213, Train Acc=0.5108, Val Acc=0.4658, Time=3.3484 sec
Epoch [46 / 100]: Train Loss=650.2139, Train Acc=0.5168, Val Acc=0.4658, Time=3.3252 sec
Epoch [47 / 100]: Train Loss=641.0405, Train Acc=0.5230, Val Acc=0.4715, Time=3.2963 sec
Epoch [48 / 100]: Train Loss=634.8574, Train Acc=0.5260, Val Acc=0.4671, Time=3.3112 sec
Epoch [49 / 100]: Train Loss=624.7569, Train Acc=0.5333, Val Acc=0.4818, Time=3.3289 sec
Epoch [50 / 100]: Train Loss=616.6585, Train Acc=0.5391, Val Acc=0.4955, Time=3.3078 sec
Epoch [51 / 100]: Train Loss=609.9359, Train Acc=0.5444, Val Acc=0.4924, Time=3.3018 sec
Epoch [52 / 100]: Train Loss=601.9779, Train Acc=0.5471, Val Acc=0.4929, Time=3.3278 sec
Epoch [53 / 100]: Train Loss=595.2681, Train Acc=0.5556, Val Acc=0.4870, Time=3.3152 sec
Epoch [54 / 100]: Train Loss=586.0509, Train Acc=0.5622, Val Acc=0.5012, Time=3.3406 sec
Epoch [55 / 100]: Train Loss=576.7164, Train Acc=0.5672, Val Acc=0.5037, Time=3.3432 sec
Epoch [56 / 100]: Train Loss=573.2111, Train Acc=0.5697, Val Acc=0.4963, Time=3.3637 sec
Epoch [57 / 100]: Train Loss=567.8513, Train Acc=0.5699, Val Acc=0.5190, Time=3.3731 sec
Epoch [58 / 100]: Train Loss=555.4507, Train Acc=0.5786, Val Acc=0.5099, Time=3.3847 sec
Epoch [59 / 100]: Train Loss=550.1698, Train Acc=0.5880, Val Acc=0.5061, Time=3.3736 sec
Epoch [60 / 100]: Train Loss=547.4856, Train Acc=0.5867, Val Acc=0.5112, Time=3.3232 sec
Epoch [61 / 100]: Train Loss=539.4541, Train Acc=0.5903, Val Acc=0.5099, Time=3.3244 sec
Epoch [62 / 100]: Train Loss=537.0230, Train Acc=0.5928, Val Acc=0.5213, Time=3.3231 sec
Epoch [63 / 100]: Train Loss=527.4556, Train Acc=0.5970, Val Acc=0.5288, Time=3.3338 sec
Epoch [64 / 100]: Train Loss=520.7951, Train Acc=0.6011, Val Acc=0.5270, Time=3.3460 sec
Epoch [65 / 100]: Train Loss=515.7618, Train Acc=0.6083, Val Acc=0.5311, Time=3.3005 sec
Epoch [66 / 100]: Train Loss=509.0431, Train Acc=0.6138, Val Acc=0.5272, Time=3.3371 sec
Epoch [67 / 100]: Train Loss=503.2433, Train Acc=0.6168, Val Acc=0.5308, Time=3.3279 sec
Epoch [68 / 100]: Train Loss=497.4267, Train Acc=0.6185, Val Acc=0.5466, Time=3.3265 sec
Epoch [69 / 100]: Train Loss=494.1902, Train Acc=0.6246, Val Acc=0.5378, Time=3.3070 sec
Epoch [70 / 100]: Train Loss=486.9533, Train Acc=0.6304, Val Acc=0.5484, Time=3.3473 sec
Epoch [71 / 100]: Train Loss=482.3389, Train Acc=0.6276, Val Acc=0.5515, Time=3.3005 sec
Epoch [72 / 100]: Train Loss=478.7310, Train Acc=0.6349, Val Acc=0.5375, Time=3.3426 sec
Epoch [73 / 100]: Train Loss=473.5775, Train Acc=0.6372, Val Acc=0.5484, Time=3.3403 sec
Epoch [74 / 100]: Train Loss=466.9977, Train Acc=0.6414, Val Acc=0.5574, Time=3.3046 sec
Epoch [75 / 100]: Train Loss=461.9237, Train Acc=0.6464, Val Acc=0.5674, Time=3.3642 sec
Epoch [76 / 100]: Train Loss=459.7089, Train Acc=0.6487, Val Acc=0.5476, Time=3.3021 sec
Epoch [77 / 100]: Train Loss=452.5423, Train Acc=0.6528, Val Acc=0.5558, Time=3.3212 sec
Epoch [78 / 100]: Train Loss=447.3588, Train Acc=0.6561, Val Acc=0.5662, Time=3.3944 sec
Epoch [79 / 100]: Train Loss=442.1858, Train Acc=0.6572, Val Acc=0.5638, Time=3.3092 sec
Epoch [80 / 100]: Train Loss=438.6429, Train Acc=0.6590, Val Acc=0.5649, Time=3.3362 sec
Epoch [81 / 100]: Train Loss=436.1836, Train Acc=0.6596, Val Acc=0.5770, Time=3.3142 sec
Epoch [82 / 100]: Train Loss=428.3987, Train Acc=0.6683, Val Acc=0.5656, Time=3.3702 sec
Epoch [83 / 100]: Train Loss=425.8476, Train Acc=0.6744, Val Acc=0.5708, Time=3.2916 sec
Epoch [84 / 100]: Train Loss=421.3908, Train Acc=0.6740, Val Acc=0.5674, Time=3.3414 sec
Epoch [85 / 100]: Train Loss=418.4522, Train Acc=0.6760, Val Acc=0.5708, Time=3.4060 sec
Epoch [86 / 100]: Train Loss=414.8002, Train Acc=0.6789, Val Acc=0.5767, Time=3.3047 sec
Epoch [87 / 100]: Train Loss=409.6759, Train Acc=0.6814, Val Acc=0.5778, Time=3.3341 sec
Epoch [88 / 100]: Train Loss=408.4295, Train Acc=0.6812, Val Acc=0.5822, Time=3.2955 sec
Epoch [89 / 100]: Train Loss=401.3884, Train Acc=0.6858, Val Acc=0.5798, Time=3.3236 sec
Epoch [90 / 100]: Train Loss=398.4525, Train Acc=0.6902, Val Acc=0.5809, Time=3.3408 sec
Epoch [91 / 100]: Train Loss=392.4733, Train Acc=0.6935, Val Acc=0.5819, Time=3.2887 sec
Epoch [92 / 100]: Train Loss=389.4209, Train Acc=0.6962, Val Acc=0.5803, Time=3.3667 sec
Epoch [93 / 100]: Train Loss=387.2734, Train Acc=0.6948, Val Acc=0.5938, Time=3.3545 sec
Epoch [94 / 100]: Train Loss=381.1579, Train Acc=0.7006, Val Acc=0.5930, Time=3.3606 sec
Epoch [95 / 100]: Train Loss=383.1377, Train Acc=0.6995, Val Acc=0.5909, Time=3.2985 sec
Epoch [96 / 100]: Train Loss=374.9469, Train Acc=0.7064, Val Acc=0.6002, Time=3.3398 sec
Epoch [97 / 100]: Train Loss=370.7209, Train Acc=0.7063, Val Acc=0.5822, Time=3.3766 sec
Epoch [98 / 100]: Train Loss=370.2582, Train Acc=0.7089, Val Acc=0.5969, Time=3.3487 sec
Epoch [99 / 100]: Train Loss=364.5788, Train Acc=0.7153, Val Acc=0.6061, Time=3.3408 sec
Epoch [100 / 100]: Train Loss=362.2600, Train Acc=0.7163, Val Acc=0.6141, Time=3.3110 sec

## Task 5: Using pretrained protein language model embeddings

In the previous tasks we are using one-hot encoded sequences as the model inputs. With the advancement of language models, many pretrained protein language models (pLM) have been widely used in protein-related problems. Below we are going to explore the usage of pLM embeddings for EC number prediction. We will use ESM-2 (https://github.com/facebookresearch/esm) to extract protein sequence embeddings. First you need to to check ESM-2's documentation to learn how to generate the embeddings using the fasta files we have provided. You should use the model `esm2_t33_650M_UR50D`, retrieve the last-layer sequence-level embedding (no need for residue-level embedding). You should generate one `.pt` file for each sequence embedding and save it in the directory `esm_embeddings`. Since the embedding generation can be time-consuming, we will use a subsampled training set (50% of the original training set) for this task. If you have adquate computational resources, you can also use the complete training set.

In [ ]:
!pip install fair-esm
!pip install biopython

Requirement already satisfied: fair-esm in C:\Users\Cole\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.0)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: biopython in C:\Users\Cole\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.86)
Requirement already satisfied: numpy in C:\Users\Cole\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from biopython) (2.4.1)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import esm
from Bio import SeqIO
from tqdm.auto import tqdm
import os
import numpy as np
import torch

def gen_emb(fasta_file, out_dir='esm_embeddings', device='cuda:0'):
    os.makedirs(out_dir, exist_ok=True)
    records = list(SeqIO.parse(fasta_file, 'fasta'))
    names = [rec.id for rec in records]
    sequences = [str(rec.seq) for rec in records]
    print(f'Number of sequences: {len(sequences)}')

    data = [(name, seq[:1000]) for name, seq in zip(names, sequences)] # Truncate to 1000 residues to shorten runtime

    ######################################################################
    # TODO: Load ESM-2 model (esm2_t33_650M_UR50D) and batch converter
    model, alphabet = esm.pretrained.esm2_t33_650M_UR50D()
    batch_converter = alphabet.get_batch_converter()
    ######################################################################

    model.to(device)
    model.eval()
    model.half() # Half-prec. to shorten runtime

    batch_size = 4 # Reduce if you are running out of cuda memory
    num_batches = int(np.ceil(len(data) / batch_size))

    for i in tqdm(range(num_batches)):
        batch = data[i * batch_size:(i + 1) * batch_size]
        names_batch, seqs_batch = zip(*batch)

        # Skip batch if all embeddings already exist
        # if all(os.path.exists(os.path.join(out_dir, f'{n}.pt')) for n in names_batch):
        #     continue

        batch_labels, batch_strs, batch_tokens = batch_converter(batch)
        batch_lens = (batch_tokens != alphabet.padding_idx).sum(1)
        batch_tokens = batch_tokens.to(device)
        
        # Extract per-residue representations (on CPU); use torch.autocast to handle 16-bit prec.
        with torch.no_grad(), torch.autocast(device_type="cuda"):
            results = model(batch_tokens, repr_layers=[33])
        token_representations = results["representations"][33].detach().cpu()
        
        # Generate per-sequence representations via averaging
        for k, tokens_len in enumerate(batch_lens):
            seq_name = names_batch[k]
            out_path = os.path.join(out_dir, f'{seq_name}.pt')

            # Skip batch operations if sequences have already been handled
            # if os.path.exists(out_path):
            #     continue

            seq_tokens = token_representations[k, :tokens_len]
            seq_mean = seq_tokens.mean(0)
            torch.save(seq_mean, out_path)

In [ ]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 5070 Laptop GPU

In [ ]:
gen_emb('train_subsample.fasta', out_dir='esm_embeddings_train')

Number of sequences: 3619

  0%|          | 0/905 [00:00<?, ?it/s]

In [ ]:
gen_emb('test_seqs.fasta', out_dir='esm_embeddings_test')

Number of sequences: 3878

  0%|          | 0/970 [00:00<?, ?it/s]

In [ ]:
df_sub = pd.read_csv('train_subsample.csv')

from Bio import SeqIO
train_sub_records = list(SeqIO.parse('train_subsample.fasta', 'fasta'))
train_sub_seq2name = {str(rec.seq): rec.id for rec in train_sub_records}

sequences_sub = df_sub['Sequence'].tolist()
labels_sub = df_sub['Label'].tolist()

seq_train_sub, seq_val_sub, label_train_sub, label_val_sub = train_test_split(
    sequences_sub, labels_sub, test_size=0.2, random_state=42
)

Construct a new dataset class to use ESM-2 embeddings.

In [ ]:
class ProteinESMDataset(Dataset):
    def __init__(self, sequences, seq2name, emb_dir, labels, ec2idx):
        super().__init__()
        self.labels = [ec2idx.get(ec, -1) for ec in labels]
        self.embeddings = []
        for seq in tqdm(sequences, desc='Loading esm embeddings'):
            name = seq2name[seq]
            emb_file = os.path.join(emb_dir, f'{name}.pt')
            emb = torch.load(emb_file)
            self.embeddings.append(emb)

    def __len__(self):
        return len(self.embeddings)

    def __getitem__(self, index):
        emb = self.embeddings[index]
        label = torch.tensor(self.labels[index], dtype=torch.long)
        return emb, label

Implement a simple MLP model to use ESM-2 embeddings as inputs for EC number prediction.

In [147]:
class MLPClassifier(nn.Module):
    def __init__(self, num_classes, input_dim=1280, hidden_dim=640, dropout_p=0.1):
        super(MLPClassifier, self).__init__()
        ######################################################################
        # TODO: linear layers
        self.layers = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout_p),
            nn.Linear(hidden_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout_p),
            nn.Linear(hidden_dim, num_classes)
        )
        ######################################################################

    def forward(self, x):
        ######################################################################
        # TODO: forward function
        ######################################################################
        return self.layers(x)

Complete the function `train_model_esm`, which trains the model taking ESM-2 embeddings as inputs.

In [148]:
def train_model_esm(model, train_dataset, val_dataset, num_classes, epochs=100, batch_size=256, lr=1e-3, patience=10, device='cuda:0'):
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=lr)

    best_acc = 0
    patience_counter = 0
    best_ckpt = None

    for epoch in range(epochs):
        model.train()
        total_loss, correct, total = 0, 0, 0

        for inputs, targets in train_loader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = None
            loss = None
            ######################################################################
            # TODO: backpropogation
            optimizer.zero_grad()
            outputs = model.forward(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            ######################################################################

            total_loss += loss.item()
            preds = outputs.argmax(dim=1)
            correct += (preds == targets).sum().item()
            total += targets.size(0)

        train_acc = correct / total

        # Validation
        model.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for sequences, labels in val_loader:
                ######################################################################
                # TODO: inference
                sequences, labels = sequences.to(device), labels.to(device)
                outputs = model(sequences)
                preds = torch.argmax(outputs, dim=1)
                ######################################################################
                correct += (preds == labels).sum().item()
                total += labels.size(0)

        val_acc = correct / total
        print(f'Epoch {epoch+1}: Train Loss={total_loss:.4f}, Train Acc={train_acc:.4f}, Val Acc={val_acc:.4f}')

        # Early stopping
        if val_acc > best_acc:
            best_acc = val_acc
            best_ckpt = model.state_dict()
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print("Early stopping triggered.")
                break

    return model, best_ckpt

Train the MLP model and generate predictions for the test set.

In [150]:
emb_dir = 'esm_embeddings'

test_sub_records = list(SeqIO.parse('test_seqs.fasta', 'fasta'))
test_sub_seq2name = {str(rec.seq): rec.id for rec in test_sub_records}

train_dataset_esm = ProteinESMDataset(seq_train_sub, train_sub_seq2name, 'esm_embeddings_train', label_train_sub, label2idx)
val_dataset_esm = ProteinESMDataset(seq_val_sub, train_sub_seq2name, 'esm_embeddings_train', label_val_sub, label2idx)

model_esm = MLPClassifier(num_classes, input_dim=1280, hidden_dim=640,dropout_p=0.3).to(device)
model_esm, best_ckpt_esm = train_model_esm(
    model_esm, train_dataset_esm, val_dataset_esm,
    num_classes=num_classes, epochs=500, batch_size=256, lr=1e-4, patience=50, device=device
)
model_esm.load_state_dict(best_ckpt_esm)

df_test = pd.read_csv('test.csv')
test_sequences = df_test['Sequence'].tolist()

test_dataset_esm = ProteinESMDataset(test_sequences, test_sub_seq2name, 'esm_embeddings_test', [label_list[0]]*len(test_sequences), label2idx)
test_loader_esm = DataLoader(test_dataset_esm, batch_size=256)

model_esm.eval()
preds = []
with torch.no_grad():
    for sequences, _ in test_loader_esm:
        ######################################################################
        # TODO: inference on the test set
        sequences = sequences.to(device)
        outputs = model_esm(sequences)
        preds.extend(torch.argmax(outputs, dim=1).cpu().tolist())
        ######################################################################


preds = [label_list[pred] for pred in preds]
df_preds = pd.DataFrame(preds)
df_preds.to_csv('test_preds_esm.csv', index=False, header=False)

Loading esm embeddings: 100%|██████████| 2895/2895 [00:00<00:00, 4872.93it/s]
Loading esm embeddings: 100%|██████████| 724/724 [00:00<00:00, 1484.74it/s]

Epoch 1: Train Loss=62.0692, Train Acc=0.0214, Val Acc=0.0124
Epoch 2: Train Loss=57.5481, Train Acc=0.1071, Val Acc=0.0442
Epoch 3: Train Loss=53.9190, Train Acc=0.2370, Val Acc=0.1519
Epoch 4: Train Loss=50.6255, Train Acc=0.3244, Val Acc=0.3246
Epoch 5: Train Loss=47.5264, Train Acc=0.4152, Val Acc=0.4337
Epoch 6: Train Loss=44.8990, Train Acc=0.4750, Val Acc=0.4779
Epoch 7: Train Loss=42.3273, Train Acc=0.5254, Val Acc=0.5138
Epoch 8: Train Loss=39.9393, Train Acc=0.5658, Val Acc=0.5345
Epoch 9: Train Loss=37.8289, Train Acc=0.5941, Val Acc=0.5428
Epoch 10: Train Loss=35.5429, Train Acc=0.6269, Val Acc=0.5594
Epoch 11: Train Loss=33.5719, Train Acc=0.6663, Val Acc=0.5787
Epoch 12: Train Loss=31.6192, Train Acc=0.6846, Val Acc=0.5912
Epoch 13: Train Loss=29.9637, Train Acc=0.7150, Val Acc=0.6257
Epoch 14: Train Loss=28.2419, Train Acc=0.7292, Val Acc=0.6298
Epoch 15: Train Loss=26.7810, Train Acc=0.7541, Val Acc=0.6340
Epoch 16: Train Loss=25.4890, Train Acc=0.7748, Val Acc=0.6519
Epoch 17: Train Loss=23.8815, Train Acc=0.7907, Val Acc=0.6602
Epoch 18: Train Loss=22.5267, Train Acc=0.8093, Val Acc=0.6699
Epoch 19: Train Loss=21.2422, Train Acc=0.8242, Val Acc=0.6878
Epoch 20: Train Loss=20.1960, Train Acc=0.8280, Val Acc=0.7017
Epoch 21: Train Loss=19.0772, Train Acc=0.8383, Val Acc=0.7058
Epoch 22: Train Loss=18.2491, Train Acc=0.8494, Val Acc=0.7113
Epoch 23: Train Loss=17.0308, Train Acc=0.8667, Val Acc=0.7210
Epoch 24: Train Loss=16.0532, Train Acc=0.8774, Val Acc=0.7307
Epoch 25: Train Loss=15.2845, Train Acc=0.8774, Val Acc=0.7334
Epoch 26: Train Loss=14.2970, Train Acc=0.8850, Val Acc=0.7348
Epoch 27: Train Loss=13.5209, Train Acc=0.8984, Val Acc=0.7417
Epoch 28: Train Loss=12.9356, Train Acc=0.9112, Val Acc=0.7555
Epoch 29: Train Loss=12.1123, Train Acc=0.9195, Val Acc=0.7569
Epoch 30: Train Loss=11.3639, Train Acc=0.9264, Val Acc=0.7693
Epoch 31: Train Loss=10.6887, Train Acc=0.9309, Val Acc=0.7707
Epoch 32: Train Loss=10.3363, Train Acc=0.9316, Val Acc=0.7707
Epoch 33: Train Loss=9.6592, Train Acc=0.9437, Val Acc=0.7762
Epoch 34: Train Loss=9.1607, Train Acc=0.9478, Val Acc=0.7804
Epoch 35: Train Loss=8.7093, Train Acc=0.9461, Val Acc=0.7845
Epoch 36: Train Loss=8.0904, Train Acc=0.9544, Val Acc=0.7914
Epoch 37: Train Loss=7.6966, Train Acc=0.9582, Val Acc=0.7956
Epoch 38: Train Loss=7.1816, Train Acc=0.9613, Val Acc=0.7970
Epoch 39: Train Loss=6.8399, Train Acc=0.9641, Val Acc=0.8025
Epoch 40: Train Loss=6.4294, Train Acc=0.9682, Val Acc=0.8039
Epoch 41: Train Loss=5.9733, Train Acc=0.9703, Val Acc=0.8094
Epoch 42: Train Loss=5.5846, Train Acc=0.9741, Val Acc=0.8135
Epoch 43: Train Loss=5.3798, Train Acc=0.9744, Val Acc=0.8163
Epoch 44: Train Loss=5.1936, Train Acc=0.9775, Val Acc=0.8177
Epoch 45: Train Loss=4.9136, Train Acc=0.9762, Val Acc=0.8204
Epoch 46: Train Loss=4.5311, Train Acc=0.9800, Val Acc=0.8218
Epoch 47: Train Loss=4.4929, Train Acc=0.9813, Val Acc=0.8246
Epoch 48: Train Loss=4.0491, Train Acc=0.9855, Val Acc=0.8246
Epoch 49: Train Loss=3.8859, Train Acc=0.9827, Val Acc=0.8246
Epoch 50: Train Loss=3.8221, Train Acc=0.9851, Val Acc=0.8287
Epoch 51: Train Loss=3.4945, Train Acc=0.9903, Val Acc=0.8301
Epoch 52: Train Loss=3.3485, Train Acc=0.9876, Val Acc=0.8315
Epoch 53: Train Loss=3.2283, Train Acc=0.9907, Val Acc=0.8329
Epoch 54: Train Loss=2.9441, Train Acc=0.9914, Val Acc=0.8370
Epoch 55: Train Loss=2.8879, Train Acc=0.9917, Val Acc=0.8412
Epoch 56: Train Loss=2.7798, Train Acc=0.9927, Val Acc=0.8398
Epoch 57: Train Loss=2.5768, Train Acc=0.9948, Val Acc=0.8412
Epoch 58: Train Loss=2.4472, Train Acc=0.9934, Val Acc=0.8425
Epoch 59: Train Loss=2.3534, Train Acc=0.9941, Val Acc=0.8481
Epoch 60: Train Loss=2.2985, Train Acc=0.9948, Val Acc=0.8467
Epoch 61: Train Loss=2.1614, Train Acc=0.9948, Val Acc=0.8467
Epoch 62: Train Loss=2.0198, Train Acc=0.9959, Val Acc=0.8481
Epoch 63: Train Loss=1.9508, Train Acc=0.9952, Val Acc=0.8508
Epoch 64: Train Loss=1.9315, Train Acc=0.9952, Val Acc=0.8494
Epoch 65: Train Loss=1.7632, Train Acc=0.9972, Val Acc=0.8536
Epoch 66: Train Loss=1.7685, Train Acc=0.9965, Val Acc=0.8536
Epoch 67: Train Loss=1.6180, Train Acc=0.9972, Val Acc=0.8536
Epoch 68: Train Loss=1.6135, Train Acc=0.9969, Val Acc=0.8550
Epoch 69: Train Loss=1.5355, Train Acc=0.9965, Val Acc=0.8522
Epoch 70: Train Loss=1.5283, Train Acc=0.9969, Val Acc=0.8536
Epoch 71: Train Loss=1.4571, Train Acc=0.9969, Val Acc=0.8564
Epoch 72: Train Loss=1.3676, Train Acc=0.9965, Val Acc=0.8536
Epoch 73: Train Loss=1.3869, Train Acc=0.9965, Val Acc=0.8508
Epoch 74: Train Loss=1.2257, Train Acc=0.9979, Val Acc=0.8494
Epoch 75: Train Loss=1.2025, Train Acc=0.9983, Val Acc=0.8536
Epoch 76: Train Loss=1.1953, Train Acc=0.9993, Val Acc=0.8536
Epoch 77: Train Loss=1.1570, Train Acc=0.9979, Val Acc=0.8550
Epoch 78: Train Loss=1.0637, Train Acc=0.9983, Val Acc=0.8536
Epoch 79: Train Loss=1.0738, Train Acc=0.9986, Val Acc=0.8536
Epoch 80: Train Loss=1.0306, Train Acc=0.9986, Val Acc=0.8522
Epoch 81: Train Loss=0.9939, Train Acc=0.9976, Val Acc=0.8550
Epoch 82: Train Loss=1.0054, Train Acc=0.9983, Val Acc=0.8508
Epoch 83: Train Loss=0.9294, Train Acc=0.9986, Val Acc=0.8536
Epoch 84: Train Loss=0.9379, Train Acc=0.9983, Val Acc=0.8494
Epoch 85: Train Loss=0.8743, Train Acc=0.9986, Val Acc=0.8508
Epoch 86: Train Loss=0.8609, Train Acc=0.9997, Val Acc=0.8508
Epoch 87: Train Loss=0.8501, Train Acc=0.9990, Val Acc=0.8536
Epoch 88: Train Loss=0.8439, Train Acc=0.9983, Val Acc=0.8536
Epoch 89: Train Loss=0.8208, Train Acc=0.9993, Val Acc=0.8564
Epoch 90: Train Loss=0.7673, Train Acc=0.9997, Val Acc=0.8577
Epoch 91: Train Loss=0.7731, Train Acc=0.9986, Val Acc=0.8577
Epoch 92: Train Loss=0.7333, Train Acc=0.9990, Val Acc=0.8550
Epoch 93: Train Loss=0.7070, Train Acc=0.9986, Val Acc=0.8550
Epoch 94: Train Loss=0.6786, Train Acc=0.9990, Val Acc=0.8550
Epoch 95: Train Loss=0.6555, Train Acc=0.9990, Val Acc=0.8577
Epoch 96: Train Loss=0.6395, Train Acc=0.9997, Val Acc=0.8564
Epoch 97: Train Loss=0.6094, Train Acc=0.9993, Val Acc=0.8564
Epoch 98: Train Loss=0.6228, Train Acc=0.9997, Val Acc=0.8536
Epoch 99: Train Loss=0.5989, Train Acc=0.9993, Val Acc=0.8536
Epoch 100: Train Loss=0.5851, Train Acc=0.9997, Val Acc=0.8536
Epoch 101: Train Loss=0.5592, Train Acc=0.9997, Val Acc=0.8550
Epoch 102: Train Loss=0.5949, Train Acc=0.9997, Val Acc=0.8550
Epoch 103: Train Loss=0.5570, Train Acc=0.9993, Val Acc=0.8550
Epoch 104: Train Loss=0.5432, Train Acc=1.0000, Val Acc=0.8536
Epoch 105: Train Loss=0.5361, Train Acc=0.9997, Val Acc=0.8536
Epoch 106: Train Loss=0.5049, Train Acc=0.9997, Val Acc=0.8522
Epoch 107: Train Loss=0.5032, Train Acc=0.9993, Val Acc=0.8536
Epoch 108: Train Loss=0.4792, Train Acc=0.9997, Val Acc=0.8550
Epoch 109: Train Loss=0.4590, Train Acc=1.0000, Val Acc=0.8564
Epoch 110: Train Loss=0.4714, Train Acc=0.9997, Val Acc=0.8564
Epoch 111: Train Loss=0.4547, Train Acc=1.0000, Val Acc=0.8550
Epoch 112: Train Loss=0.4326, Train Acc=0.9993, Val Acc=0.8550
Epoch 113: Train Loss=0.4473, Train Acc=0.9997, Val Acc=0.8550
Epoch 114: Train Loss=0.4525, Train Acc=0.9986, Val Acc=0.8577
Epoch 115: Train Loss=0.4077, Train Acc=0.9997, Val Acc=0.8550
Epoch 116: Train Loss=0.4350, Train Acc=0.9993, Val Acc=0.8536
Epoch 117: Train Loss=0.4136, Train Acc=0.9997, Val Acc=0.8550
Epoch 118: Train Loss=0.4360, Train Acc=0.9990, Val Acc=0.8550
Epoch 119: Train Loss=0.3934, Train Acc=1.0000, Val Acc=0.8564
Epoch 120: Train Loss=0.3690, Train Acc=0.9993, Val Acc=0.8564
Epoch 121: Train Loss=0.3943, Train Acc=0.9997, Val Acc=0.8577
Epoch 122: Train Loss=0.3514, Train Acc=0.9997, Val Acc=0.8564
Epoch 123: Train Loss=0.3714, Train Acc=0.9997, Val Acc=0.8577
Epoch 124: Train Loss=0.3588, Train Acc=0.9997, Val Acc=0.8577
Epoch 125: Train Loss=0.3382, Train Acc=0.9997, Val Acc=0.8564
Epoch 126: Train Loss=0.3459, Train Acc=1.0000, Val Acc=0.8550
Epoch 127: Train Loss=0.3156, Train Acc=1.0000, Val Acc=0.8550
Epoch 128: Train Loss=0.3273, Train Acc=0.9997, Val Acc=0.8550
Epoch 129: Train Loss=0.3170, Train Acc=1.0000, Val Acc=0.8536
Epoch 130: Train Loss=0.3083, Train Acc=1.0000, Val Acc=0.8564
Epoch 131: Train Loss=0.3006, Train Acc=1.0000, Val Acc=0.8522
Epoch 132: Train Loss=0.2964, Train Acc=1.0000, Val Acc=0.8577
Epoch 133: Train Loss=0.3116, Train Acc=0.9997, Val Acc=0.8591
Epoch 134: Train Loss=0.3027, Train Acc=1.0000, Val Acc=0.8591
Epoch 135: Train Loss=0.2880, Train Acc=1.0000, Val Acc=0.8564
Epoch 136: Train Loss=0.2825, Train Acc=1.0000, Val Acc=0.8577
Epoch 137: Train Loss=0.2721, Train Acc=1.0000, Val Acc=0.8591
Epoch 138: Train Loss=0.2798, Train Acc=0.9997, Val Acc=0.8577
Epoch 139: Train Loss=0.2774, Train Acc=1.0000, Val Acc=0.8577
Epoch 140: Train Loss=0.2849, Train Acc=0.9993, Val Acc=0.8577
Epoch 141: Train Loss=0.2587, Train Acc=1.0000, Val Acc=0.8564
Epoch 142: Train Loss=0.2698, Train Acc=1.0000, Val Acc=0.8591
Epoch 143: Train Loss=0.2544, Train Acc=0.9990, Val Acc=0.8605
Epoch 144: Train Loss=0.2564, Train Acc=0.9997, Val Acc=0.8591
Epoch 145: Train Loss=0.2601, Train Acc=0.9997, Val Acc=0.8591
Epoch 146: Train Loss=0.2436, Train Acc=1.0000, Val Acc=0.8619
Epoch 147: Train Loss=0.2383, Train Acc=1.0000, Val Acc=0.8619
Epoch 148: Train Loss=0.2504, Train Acc=1.0000, Val Acc=0.8619
Epoch 149: Train Loss=0.2271, Train Acc=1.0000, Val Acc=0.8605
Epoch 150: Train Loss=0.2278, Train Acc=1.0000, Val Acc=0.8619
Epoch 151: Train Loss=0.2188, Train Acc=1.0000, Val Acc=0.8619
Epoch 152: Train Loss=0.2148, Train Acc=1.0000, Val Acc=0.8619
Epoch 153: Train Loss=0.2167, Train Acc=1.0000, Val Acc=0.8591
Epoch 154: Train Loss=0.2187, Train Acc=1.0000, Val Acc=0.8577
Epoch 155: Train Loss=0.2132, Train Acc=1.0000, Val Acc=0.8605
Epoch 156: Train Loss=0.2051, Train Acc=1.0000, Val Acc=0.8605
Epoch 157: Train Loss=0.1997, Train Acc=1.0000, Val Acc=0.8605
Epoch 158: Train Loss=0.1949, Train Acc=1.0000, Val Acc=0.8605
Epoch 159: Train Loss=0.2016, Train Acc=1.0000, Val Acc=0.8591
Epoch 160: Train Loss=0.2083, Train Acc=0.9997, Val Acc=0.8577
Epoch 161: Train Loss=0.1969, Train Acc=1.0000, Val Acc=0.8577
Epoch 162: Train Loss=0.2016, Train Acc=0.9997, Val Acc=0.8577
Epoch 163: Train Loss=0.1867, Train Acc=1.0000, Val Acc=0.8577
Epoch 164: Train Loss=0.1838, Train Acc=0.9993, Val Acc=0.8564
Epoch 165: Train Loss=0.1836, Train Acc=1.0000, Val Acc=0.8564
Epoch 166: Train Loss=0.1820, Train Acc=1.0000, Val Acc=0.8605
Epoch 167: Train Loss=0.1778, Train Acc=1.0000, Val Acc=0.8591
Epoch 168: Train Loss=0.1749, Train Acc=1.0000, Val Acc=0.8591
Epoch 169: Train Loss=0.1707, Train Acc=1.0000, Val Acc=0.8591
Epoch 170: Train Loss=0.1628, Train Acc=1.0000, Val Acc=0.8591
Epoch 171: Train Loss=0.1629, Train Acc=1.0000, Val Acc=0.8591
Epoch 172: Train Loss=0.1682, Train Acc=1.0000, Val Acc=0.8605
Epoch 173: Train Loss=0.1641, Train Acc=1.0000, Val Acc=0.8591
Epoch 174: Train Loss=0.1508, Train Acc=1.0000, Val Acc=0.8591
Epoch 175: Train Loss=0.1591, Train Acc=1.0000, Val Acc=0.8591
Epoch 176: Train Loss=0.1629, Train Acc=1.0000, Val Acc=0.8591
Epoch 177: Train Loss=0.1647, Train Acc=1.0000, Val Acc=0.8605
Epoch 178: Train Loss=0.1457, Train Acc=1.0000, Val Acc=0.8591
Epoch 179: Train Loss=0.1433, Train Acc=1.0000, Val Acc=0.8591
Epoch 180: Train Loss=0.1476, Train Acc=0.9997, Val Acc=0.8619
Epoch 181: Train Loss=0.1495, Train Acc=1.0000, Val Acc=0.8591
Epoch 182: Train Loss=0.1408, Train Acc=1.0000, Val Acc=0.8577
Epoch 183: Train Loss=0.1424, Train Acc=1.0000, Val Acc=0.8605
Epoch 184: Train Loss=0.1406, Train Acc=1.0000, Val Acc=0.8591
Epoch 185: Train Loss=0.1382, Train Acc=1.0000, Val Acc=0.8605
Epoch 186: Train Loss=0.1340, Train Acc=1.0000, Val Acc=0.8591
Epoch 187: Train Loss=0.1296, Train Acc=1.0000, Val Acc=0.8577
Epoch 188: Train Loss=0.1343, Train Acc=1.0000, Val Acc=0.8591
Epoch 189: Train Loss=0.1255, Train Acc=1.0000, Val Acc=0.8564
Epoch 190: Train Loss=0.1336, Train Acc=1.0000, Val Acc=0.8564
Epoch 191: Train Loss=0.1202, Train Acc=1.0000, Val Acc=0.8550
Epoch 192: Train Loss=0.1270, Train Acc=0.9997, Val Acc=0.8577
Epoch 193: Train Loss=0.1258, Train Acc=1.0000, Val Acc=0.8591
Epoch 194: Train Loss=0.1227, Train Acc=0.9997, Val Acc=0.8591
Epoch 195: Train Loss=0.1219, Train Acc=1.0000, Val Acc=0.8577
Epoch 196: Train Loss=0.1200, Train Acc=1.0000, Val Acc=0.8591
Early stopping triggered.

Loading esm embeddings: 100%|██████████| 3878/3878 [00:00<00:00, 5013.46it/s]

## Grading

### Task 1 (4 points)
Task 1 will be graded by the correctness of the function `one_hot_encode`.

### Task 2 (9 points)
Tasks 2-5 will be graded by the accuracy of the predictions made by each model on the test set.

- Accuracy >= 0.7, 9 points
- Accuracy >= 0.65, 8.5 points
- Accuracy >= 0.6, 7 points
- Accuracy >= 0.55, 6 points
- Accuracy < 0.55, 0 points

### Task 3 (9 points)

- Accuracy >= 0.7, 9 points
- Accuracy >= 0.65, 8.5 points
- Accuracy >= 0.6, 7 points
- Accuracy >= 0.55, 6 points
- Accuracy < 0.55, 0 points

### Task 4 (9 points)

- Accuracy >= 0.55, 9 points
- Accuracy >= 0.50, 7 points
- Accuracy >= 0.45, 5 points
- Accuracy < 0.45, 0 points

### Task 5 (9 points)

- Accuracy >= 0.85, 9 points
- Accuracy >= 0.8, 7 points
- Accuracy >= 0.75, 5 points
- Accuracy < 0.75, 0 points

## Submission

After completing all the tasks, you need to submit five files to Gradescope:
- `hw2_nn.ipynb`, the notebook file with all tasks completed.
- `test_preds_attention.csv`
- `test_preds_transformer.csv`
- `test_preds_cnn.csv`
- `test_preds_esm.csv`

Note that the four `.csv` files will be automatically generated when running this notebook, do not change the codes regarding the save of the prediction results. **DO NOT** submit the files in a zip file, please submit them individually to Gradescope.