# ESM C Implementation (62% Train Spearman R, 43% Validation Spearman R)

Within each cycle of active learning:

1. Collect training data (original training data + your query data).

2. Train a prediction model to predict the DMS_score for each mutant (e.g., M0A).

3. Use the trained model to predict the score for all mutant in the test set.

4. Select query mutants for next round based on certain criteria. You may want to make sure you don't query the same mutant twice as you only have limited chances to make queries.

In [39]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import DataLoader, Dataset
import random
from copy import deepcopy
import pandas as pd
from scipy.stats import spearmanr
import argparse
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.linear_model import LinearRegression

import os
from tqdm.auto import tqdm

from esm.models.esmc import ESMC
from esm.sdk.api import ESMProtein, LogitsConfig

## 1. Collect Training Data

In [2]:
#with open('Hackathon_data/Hackathon_data/sequence.fasta', 'r') as f:
with open('sequence.fasta', 'r') as f:
  data = f.readlines()

sequence_wt = data[1].strip()
sequence_wt

'MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLREKMRRRLESGDKWFSLEFFPPRTAEGAVNLISRFDRMAAGGPLYIDVTWHPAGDPGSDKETSSMMIASTAVNYCGLETILHMTCCRQRLEEITGHLHKAKQLGLKNIMALRGDPIGDQWEEEEGGFNYAVDLVKHIRSEFGDYFDICVAGYPKGHPEAGSFEADLKHLKEKVSAGADFIITQLFFEADTFFRFVKACTDMGITCPIVPGIFPIQGYHSLRQLVKLSKLEVPQEIKDVIEPIKDNDAAIRNYGIELAVSLCQELLASGLVPGLHFYTLNREMATTEVLKRLGMWTEDPRRPLPWALSAHPKRREEDVRPIFWASRPKSYIYRTQEWDEFPNGRWGNSSSPAFGELKDYYLFYLKSKSPKEELLKMWGEELTSEESVFEVFVLYLSGEPNRNGHKVTCLPWNDEPLAAETSLLKEELLRVNRQGILTINSQPNINGKPSSDPIVGWGPSGGYVFQKAYLEFFTSRETAEALLQVLKKYELRVNYHLVNVKGENITNAPELQPNAVTWGIFPGREIIQPTVVDPVSFMFWKDEAFALWIERWGKLYEEESPSRTIIQYIHDNYFLVNLVDNDFPLDNCLWQVVEDTLELLNRPTQNARETEAP'

In [3]:
len(sequence_wt)

656

In [4]:
def get_mutated_sequence(mut, sequence_wt):
    '''
    Adds the specified mutation into the wild-type sequence.

    Params:
        mut (str): The mutation to be applied.
        sequence_wt (str): The wild-type sequence to which the mutation will be applied.
    Returns:
        A deep copy of the mutated sequence string.
    '''
    # wt - wild type; pos - position; mt - mutation
    wt, pos, mt = mut[0], int(mut[1:-1]), mut[-1]

    sequence = deepcopy(sequence_wt)

    return sequence[:pos] + mt + sequence[pos+1:]

In [5]:
#df_train = pd.read_csv('Hackathon_data/Hackathon_data/train.csv')
df_train = pd.read_csv('train.csv')
df_train['sequence'] = df_train.mutant.apply(lambda x: get_mutated_sequence(x, sequence_wt))
df_train

     mutant  DMS_score                                           sequence
0       M0Y     0.2730  YVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1       M0W     0.2857  WVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
2       M0V     0.2153  VVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
3       M0T     0.3122  TVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
4       M0S     0.2180  SVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
...     ...        ...                                                ...
1135  P347D     0.3876  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1136  P347C     0.1837  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1137  P347A     0.4611  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1138  P347M     0.2412  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1139  P347H     0.1512  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...

[1140 rows x 3 columns]

In [6]:
#df_test = pd.read_csv('Hackathon_data/Hackathon_data/test.csv')
df_test = pd.read_csv('test.csv')
df_test['sequence'] = df_test.mutant.apply(lambda x: get_mutated_sequence(x, sequence_wt))
df_test

      mutant                                           sequence
0        V1D  MDNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
1        V1Y  MYNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
2        V1C  MCNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
3        V1A  MANEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
4        V1E  MENEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
...      ...                                                ...
11319  P655S  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
11320  P655T  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
11321  P655V  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
11322  P655A  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
11323  P655W  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...

[11324 rows x 2 columns]

In [7]:
# TODO: integrate the query data that you acquired each round into df_train

## 2. Train a Prediction Model

### Hyperparameters

In [8]:
seq_length = 656
seed = 0 # seed for splitting the validation set
val_ratio = 0.2 # proportion of validation set

### ProteinDataset
Convert amino acids to machine-readable data via embedding space.

In [9]:
def gen_emb_from_df(df, out_dir="esm_c_embeddings_variants", device="cuda:0", batch_size=8):
    '''
    Generate and cache ESM-C sequence embeddings for each unique mutant.
    Saves one mean-pooled embedding tensor per mutant to out_dir/{mutant}.pt.
    '''
    os.makedirs(out_dir, exist_ok=True)

    if isinstance(device, torch.device):
        use_cuda = device.type == "cuda"
    else:
        use_cuda = str(device).startswith("cuda")
    device = torch.device(device) if not isinstance(device, torch.device) else device

    # Each item is (name_for_file, sequence)
    data = [(m, s[:1000]) for m, s in df[["mutant", "sequence"]].drop_duplicates().values]
    print(f"Number of unique variants: {len(data)}")

    # Instantiate 600-million-parameter ESM-C model
    model = ESMC.from_pretrained("esmc_600m").to(device).eval()
    if use_cuda:
        model.half()  # Half-prec. to reduce GPU memory and runtime

    for i in tqdm(range(int(np.ceil(len(data) / batch_size)))):
        batch = data[i * batch_size:(i + 1) * batch_size]

        # Cache skip
        if all(os.path.exists(os.path.join(out_dir, f"{name}.pt")) for name, _ in batch):
            continue

        for name, sequence in batch:
            path = os.path.join(out_dir, f"{name}.pt")
            if os.path.exists(path):
                continue

            protein = ESMProtein(sequence=sequence)

            with torch.no_grad():
                protein_tensor = model.encode(protein)
                model_output = model.logits(
                    protein_tensor,
                    LogitsConfig(sequence=True, return_embeddings=True),
                )

            seq_emb = model_output.embeddings

            # Handle both [L, D] and [1, L, D] output shapes.
            if seq_emb.ndim == 3:
                seq_emb = seq_emb[0]
            seq_mean = seq_emb.float().mean(dim=0).detach().cpu()

            torch.save(seq_mean, path)

class DmsESMDataset(Dataset):
    def __init__(self, df, emb_dir, is_train=True):
        self.df = df.reset_index(drop=True)
        self.emb_dir = emb_dir
        self.is_train = is_train

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        mutant = self.df.loc[idx, "mutant"]
        emb = torch.load(os.path.join(self.emb_dir, f"{mutant}.pt")).float()
        if self.is_train:
            y = torch.tensor(self.df.loc[idx, "DMS_score"], dtype=torch.float32)
            return emb, y
        return emb, torch.tensor(0.0, dtype=torch.float32)

In [10]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("No CUDA device found; using CPU.")

# Run on GPU 0 when available
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

True
NVIDIA GeForce RTX 5070 Laptop GPU

In [11]:
# Combine our datasets for embedding, them split them into train / test sets afterward. Each has mutated sequence variants stored as a separate .pt embedding.
all_df = pd.concat(
    [df_train[["mutant", "sequence"]], df_test[["mutant", "sequence"]]],
    ignore_index=True
).drop_duplicates("mutant")

gen_emb_from_df(all_df, out_dir="esm_c_embeddings_variants", device=device, batch_size=8)

Number of unique variants: 12464

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

  0%|          | 0/1558 [00:00<?, ?it/s]

In [12]:
# gen_emb('Hackathon_Data/Hackathon_data/sequence.fasta', out_dir='esm_embeddings_train')
# gen_emb('Hackathon_Data/Hackathon_data/', out_dir='esm_embeddings_test')

In [13]:
# Use simple MLP model to predict from ESM C embeddings.
class MLPRegressor(nn.Module):
    def __init__(self, input_dim=1280, hidden_dim=640, dropout_p=0.1):
        super(MLPRegressor, self).__init__()

        # Only need to predict a single fitness score every time.
        output_dim = 1

        self.layers = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout_p),
            nn.Linear(hidden_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout_p),
            nn.Linear(hidden_dim, output_dim),
            nn.Sigmoid() # Ensures fitness scores in range (0,1).
        )

    def forward(self, x):
        return self.layers(x)

In [ ]:
'''
Params:
    model (torch.nn):               The untrained Fully-Connected Neural Network (FCN)
    train_dataset (DmsESMDataset):  The training dataset
    val_dataset (DmsESMDataset):    The validation dataset
    epochs (int):                   The number of epochs over which to train
    batch_size (int):               The number of batches in which to split the input data
    lr (float):                     The learning rate
    patience (int):                 The number of epochs to wait while the validation metric shows no improvement
    alpha (float):                  The Exponential Moving Average (EMA) weight by which the Spearman R is smoothed
    device (str):                   The CPU / GPU on which to run the model
Returns:
    model (torch.nn):               The trained FCN
    best_ckpt (dictionary):         Dictionary saving the best parameters
'''
def train_model_esm(model, train_dataset, val_dataset, epochs=100, batch_size=256, lr=1e-3, patience=10, alpha=0.3, device='cuda:0'):
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size)

    # Use MSE loss to handle bounded regression.
    criterion = nn.MSELoss()
    optimizer = optim.AdamW(model.parameters(), lr=lr)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='max', factor=0.5, patience=4)

    best_val_spearman = -np.inf
    best_ckpt = None
    patience_counter = 0
    val_spearman_ema = None

    for epoch in range(epochs):
        model.train()
        train_losses = []
        train_preds = []
        train_targets = []

        for inputs, targets in train_loader:
            inputs = inputs.to(device)
            targets = targets.to(device).float()

            optimizer.zero_grad()
            outputs = model(inputs).squeeze(-1)
            loss = criterion(outputs, targets)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0, norm_type=2.0)
            optimizer.step()

            train_losses.append(loss.item())
            train_preds.append(outputs.detach().cpu())
            train_targets.append(targets.detach().cpu())

        train_preds = torch.cat(train_preds).numpy()
        train_targets = torch.cat(train_targets).numpy()
        train_spearman = spearmanr(train_preds, train_targets).statistic

        # Validation
        model.eval()
        val_losses = []
        val_preds = []
        val_targets = []
        with torch.no_grad():
            for inputs, targets in val_loader:
                inputs = inputs.to(device)
                targets = targets.to(device).float()
                outputs = model(inputs).squeeze(-1)

                val_losses.append(criterion(outputs, targets).item())
                val_preds.append(outputs.detach().cpu())
                val_targets.append(targets.detach().cpu())

        val_preds = torch.cat(val_preds).numpy()
        val_targets = torch.cat(val_targets).numpy()
        val_spearman = spearmanr(val_preds, val_targets).statistic
        mean_train_loss = float(np.mean(train_losses))
        mean_val_loss = float(np.mean(val_losses))

        # Set moving average old value if it doesn't exist yet; prevents initial validation Spearman R from being artificially low.
        if val_spearman_ema == None:
            val_spearman_ema = val_spearman

        val_spearman_ema = alpha * val_spearman + (1 - alpha) * val_spearman_ema

        scheduler.step(val_spearman_ema)

        if np.isnan(train_spearman):
            train_spearman = 0.0
        if np.isnan(val_spearman):
            val_spearman = -1.0

        print(
            f"Epoch {epoch+1}: "
            f"Train Loss={mean_train_loss:.4f}, Train Spearman={train_spearman:.4f}, "
            f"Val Loss={mean_val_loss:.4f}, Val Spearman={val_spearman:.4f}, "
            f"LR={optimizer.param_groups[0]["lr"]}"
        )

        # Early stopping on validation Spearman (ranking quality)
        if val_spearman > best_val_spearman:
            best_val_spearman = val_spearman
            best_ckpt = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print("Early stopping triggered.")
                break

    if best_ckpt is None:
        best_ckpt = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}

    return model, best_ckpt

In [43]:
# Split data into train and validation sets, then form DmsESMDataset() classes from each.
df_train_split, df_val_split = train_test_split(
    df_train, test_size=val_ratio, random_state=seed, shuffle=True
)

train_ds = DmsESMDataset(df_train_split, "esm_c_embeddings_variants", is_train=True)
val_ds = DmsESMDataset(df_val_split, "esm_c_embeddings_variants", is_train=True)
test_ds = DmsESMDataset(df_test, "esm_c_embeddings_variants", is_train=False)

test_loader = DataLoader(test_ds, batch_size=256, shuffle=False)

In [ ]:
# --------------- Train our model ---------------
model_esm = MLPRegressor(input_dim=1152,
                          hidden_dim=640,
                          dropout_p=0.3).to(device)
# TODO Currently using test values to make sure this works.
model_esm, best_ckpt_esm = train_model_esm(
    model_esm,
    train_ds,
    val_ds,
    epochs=500,  # 10
    batch_size=256,
    lr=5e-3,  # 1e-3
    patience=40,  # 5
    device=device,
 )
model_esm.load_state_dict(best_ckpt_esm)


# --------------- Test our model ---------------
model_esm.eval()
preds = []
with torch.no_grad():
    for sequences, _ in test_loader:
        # Inference on the test set
        sequences = sequences.to(device)
        outputs = model_esm(sequences)
        dms_score_pred = outputs.squeeze(-1).cpu().numpy()
        preds.extend(dms_score_pred.tolist())

df_pred = df_test.copy()
df_pred["DMS_score_predicted"] = preds

Epoch 1: Train Loss=0.1247, Train Spearman=0.0368, Val Loss=0.0916, Val Spearman=-0.0936, LR=0.005
Epoch 2: Train Loss=0.0717, Train Spearman=0.0550, Val Loss=0.0503, Val Spearman=0.0298, LR=0.005
Epoch 3: Train Loss=0.0652, Train Spearman=0.1482, Val Loss=0.0538, Val Spearman=0.0580, LR=0.005
Epoch 4: Train Loss=0.0618, Train Spearman=0.1990, Val Loss=0.0564, Val Spearman=0.0840, LR=0.005
Epoch 5: Train Loss=0.0562, Train Spearman=0.2290, Val Loss=0.0558, Val Spearman=0.1038, LR=0.005
Epoch 6: Train Loss=0.0533, Train Spearman=0.2561, Val Loss=0.0551, Val Spearman=0.1172, LR=0.005
Epoch 7: Train Loss=0.0492, Train Spearman=0.2855, Val Loss=0.0548, Val Spearman=0.1396, LR=0.005
Epoch 8: Train Loss=0.0461, Train Spearman=0.3117, Val Loss=0.0563, Val Spearman=0.1526, LR=0.005
Epoch 9: Train Loss=0.0441, Train Spearman=0.3295, Val Loss=0.0578, Val Spearman=0.1493, LR=0.005
Epoch 10: Train Loss=0.0422, Train Spearman=0.3363, Val Loss=0.0603, Val Spearman=0.1397, LR=0.005
Epoch 11: Train Loss=0.0419, Train Spearman=0.3559, Val Loss=0.0619, Val Spearman=0.1381, LR=0.005
Epoch 12: Train Loss=0.0400, Train Spearman=0.3646, Val Loss=0.0631, Val Spearman=0.1383, LR=0.005
Epoch 13: Train Loss=0.0379, Train Spearman=0.3880, Val Loss=0.0644, Val Spearman=0.1484, LR=0.005
Epoch 14: Train Loss=0.0376, Train Spearman=0.4033, Val Loss=0.0629, Val Spearman=0.1785, LR=0.005
Epoch 15: Train Loss=0.0352, Train Spearman=0.4264, Val Loss=0.0643, Val Spearman=0.1746, LR=0.005
Epoch 16: Train Loss=0.0340, Train Spearman=0.4308, Val Loss=0.0628, Val Spearman=0.1794, LR=0.005
Epoch 17: Train Loss=0.0328, Train Spearman=0.4512, Val Loss=0.0584, Val Spearman=0.2043, LR=0.005
Epoch 18: Train Loss=0.0323, Train Spearman=0.4594, Val Loss=0.0576, Val Spearman=0.2025, LR=0.005
Epoch 19: Train Loss=0.0320, Train Spearman=0.4729, Val Loss=0.0516, Val Spearman=0.2673, LR=0.005
Epoch 20: Train Loss=0.0304, Train Spearman=0.4803, Val Loss=0.0509, Val Spearman=0.2876, LR=0.005
Epoch 21: Train Loss=0.0299, Train Spearman=0.4863, Val Loss=0.0554, Val Spearman=0.2799, LR=0.005
Epoch 22: Train Loss=0.0279, Train Spearman=0.5043, Val Loss=0.0686, Val Spearman=0.2883, LR=0.005
Epoch 23: Train Loss=0.0282, Train Spearman=0.4968, Val Loss=0.0702, Val Spearman=0.2802, LR=0.005
Epoch 24: Train Loss=0.0262, Train Spearman=0.5312, Val Loss=0.0692, Val Spearman=0.2761, LR=0.005
Epoch 25: Train Loss=0.0266, Train Spearman=0.5257, Val Loss=0.0993, Val Spearman=0.2655, LR=0.005
Epoch 26: Train Loss=0.0251, Train Spearman=0.5315, Val Loss=0.1041, Val Spearman=0.2728, LR=0.005
Epoch 27: Train Loss=0.0242, Train Spearman=0.5378, Val Loss=0.1059, Val Spearman=0.2937, LR=0.005
Epoch 28: Train Loss=0.0241, Train Spearman=0.5400, Val Loss=0.1059, Val Spearman=0.3406, LR=0.005
Epoch 29: Train Loss=0.0227, Train Spearman=0.5498, Val Loss=0.1059, Val Spearman=0.3308, LR=0.005
Epoch 30: Train Loss=0.0216, Train Spearman=0.5772, Val Loss=0.1056, Val Spearman=0.3615, LR=0.005
Epoch 31: Train Loss=0.0229, Train Spearman=0.5650, Val Loss=0.1046, Val Spearman=0.3517, LR=0.005
Epoch 32: Train Loss=0.0221, Train Spearman=0.5742, Val Loss=0.0981, Val Spearman=0.3605, LR=0.005
Epoch 33: Train Loss=0.0213, Train Spearman=0.5792, Val Loss=0.1014, Val Spearman=0.3530, LR=0.005
Epoch 34: Train Loss=0.0214, Train Spearman=0.5842, Val Loss=0.1054, Val Spearman=0.3408, LR=0.005
Epoch 35: Train Loss=0.0213, Train Spearman=0.5828, Val Loss=0.1060, Val Spearman=0.2694, LR=0.005
Epoch 36: Train Loss=0.0203, Train Spearman=0.5903, Val Loss=0.1060, Val Spearman=0.3451, LR=0.005
Epoch 37: Train Loss=0.0186, Train Spearman=0.6103, Val Loss=0.1058, Val Spearman=0.3288, LR=0.005
Epoch 38: Train Loss=0.0193, Train Spearman=0.5969, Val Loss=0.1056, Val Spearman=0.3667, LR=0.0025
Epoch 39: Train Loss=0.0183, Train Spearman=0.6177, Val Loss=0.0953, Val Spearman=0.3709, LR=0.0025
Epoch 40: Train Loss=0.0181, Train Spearman=0.6179, Val Loss=0.0720, Val Spearman=0.3523, LR=0.0025
Epoch 41: Train Loss=0.0178, Train Spearman=0.6323, Val Loss=0.0711, Val Spearman=0.3611, LR=0.0025
Epoch 42: Train Loss=0.0177, Train Spearman=0.6310, Val Loss=0.0486, Val Spearman=0.3094, LR=0.0025
Epoch 43: Train Loss=0.0164, Train Spearman=0.6356, Val Loss=0.0589, Val Spearman=0.3080, LR=0.0025
Epoch 44: Train Loss=0.0169, Train Spearman=0.6359, Val Loss=0.0602, Val Spearman=0.3430, LR=0.0025
Epoch 45: Train Loss=0.0173, Train Spearman=0.6460, Val Loss=0.0582, Val Spearman=0.3811, LR=0.0025
Epoch 46: Train Loss=0.0154, Train Spearman=0.6422, Val Loss=0.0649, Val Spearman=0.3594, LR=0.00125
Epoch 47: Train Loss=0.0161, Train Spearman=0.6455, Val Loss=0.0570, Val Spearman=0.3859, LR=0.00125
Epoch 48: Train Loss=0.0155, Train Spearman=0.6544, Val Loss=0.0456, Val Spearman=0.3944, LR=0.00125
Epoch 49: Train Loss=0.0156, Train Spearman=0.6518, Val Loss=0.0634, Val Spearman=0.3707, LR=0.00125
Epoch 50: Train Loss=0.0144, Train Spearman=0.6600, Val Loss=0.0597, Val Spearman=0.3830, LR=0.00125
Epoch 51: Train Loss=0.0147, Train Spearman=0.6649, Val Loss=0.0484, Val Spearman=0.4070, LR=0.00125
Epoch 52: Train Loss=0.0150, Train Spearman=0.6672, Val Loss=0.0847, Val Spearman=0.3772, LR=0.00125
Epoch 53: Train Loss=0.0151, Train Spearman=0.6535, Val Loss=0.0943, Val Spearman=0.3268, LR=0.00125
Epoch 54: Train Loss=0.0145, Train Spearman=0.6578, Val Loss=0.0988, Val Spearman=0.3320, LR=0.00125
Epoch 55: Train Loss=0.0144, Train Spearman=0.6586, Val Loss=0.0988, Val Spearman=0.3393, LR=0.00125
Epoch 56: Train Loss=0.0137, Train Spearman=0.6628, Val Loss=0.0660, Val Spearman=0.3512, LR=0.000625
Epoch 57: Train Loss=0.0139, Train Spearman=0.6627, Val Loss=0.0562, Val Spearman=0.3570, LR=0.000625
Epoch 58: Train Loss=0.0143, Train Spearman=0.6642, Val Loss=0.0520, Val Spearman=0.3747, LR=0.000625
Epoch 59: Train Loss=0.0142, Train Spearman=0.6658, Val Loss=0.0553, Val Spearman=0.3753, LR=0.000625
Epoch 60: Train Loss=0.0150, Train Spearman=0.6567, Val Loss=0.0613, Val Spearman=0.3668, LR=0.000625
Epoch 61: Train Loss=0.0148, Train Spearman=0.6593, Val Loss=0.0589, Val Spearman=0.3501, LR=0.0003125
Epoch 62: Train Loss=0.0134, Train Spearman=0.6714, Val Loss=0.0593, Val Spearman=0.3461, LR=0.0003125
Epoch 63: Train Loss=0.0140, Train Spearman=0.6723, Val Loss=0.0577, Val Spearman=0.3477, LR=0.0003125
Epoch 64: Train Loss=0.0139, Train Spearman=0.6641, Val Loss=0.0504, Val Spearman=0.3684, LR=0.0003125
Epoch 65: Train Loss=0.0146, Train Spearman=0.6713, Val Loss=0.0486, Val Spearman=0.3784, LR=0.0003125
Epoch 66: Train Loss=0.0137, Train Spearman=0.6767, Val Loss=0.0488, Val Spearman=0.3813, LR=0.00015625
Epoch 67: Train Loss=0.0141, Train Spearman=0.6733, Val Loss=0.0494, Val Spearman=0.3869, LR=0.00015625
Epoch 68: Train Loss=0.0137, Train Spearman=0.6721, Val Loss=0.0506, Val Spearman=0.3877, LR=0.00015625
Epoch 69: Train Loss=0.0134, Train Spearman=0.6735, Val Loss=0.0526, Val Spearman=0.3910, LR=0.00015625
Epoch 70: Train Loss=0.0132, Train Spearman=0.6719, Val Loss=0.0512, Val Spearman=0.3884, LR=0.00015625
Epoch 71: Train Loss=0.0133, Train Spearman=0.6781, Val Loss=0.0504, Val Spearman=0.3853, LR=7.8125e-05
Epoch 72: Train Loss=0.0131, Train Spearman=0.6765, Val Loss=0.0511, Val Spearman=0.3859, LR=7.8125e-05
Epoch 73: Train Loss=0.0134, Train Spearman=0.6742, Val Loss=0.0521, Val Spearman=0.3839, LR=7.8125e-05
Epoch 74: Train Loss=0.0141, Train Spearman=0.6684, Val Loss=0.0526, Val Spearman=0.3846, LR=7.8125e-05
Epoch 75: Train Loss=0.0137, Train Spearman=0.6679, Val Loss=0.0529, Val Spearman=0.3850, LR=7.8125e-05
Epoch 76: Train Loss=0.0137, Train Spearman=0.6738, Val Loss=0.0530, Val Spearman=0.3862, LR=7.8125e-05
Epoch 77: Train Loss=0.0136, Train Spearman=0.6674, Val Loss=0.0529, Val Spearman=0.3874, LR=7.8125e-05
Epoch 78: Train Loss=0.0133, Train Spearman=0.6765, Val Loss=0.0532, Val Spearman=0.3864, LR=7.8125e-05
Epoch 79: Train Loss=0.0138, Train Spearman=0.6713, Val Loss=0.0537, Val Spearman=0.3864, LR=7.8125e-05
Epoch 80: Train Loss=0.0135, Train Spearman=0.6702, Val Loss=0.0539, Val Spearman=0.3866, LR=7.8125e-05
Epoch 81: Train Loss=0.0129, Train Spearman=0.6757, Val Loss=0.0527, Val Spearman=0.3897, LR=7.8125e-05
Epoch 82: Train Loss=0.0141, Train Spearman=0.6769, Val Loss=0.0521, Val Spearman=0.3929, LR=7.8125e-05
Epoch 83: Train Loss=0.0143, Train Spearman=0.6746, Val Loss=0.0517, Val Spearman=0.3946, LR=7.8125e-05
Epoch 84: Train Loss=0.0127, Train Spearman=0.6785, Val Loss=0.0517, Val Spearman=0.3925, LR=7.8125e-05
Epoch 85: Train Loss=0.0126, Train Spearman=0.6789, Val Loss=0.0522, Val Spearman=0.3884, LR=7.8125e-05
Epoch 86: Train Loss=0.0141, Train Spearman=0.6755, Val Loss=0.0525, Val Spearman=0.3894, LR=7.8125e-05
Epoch 87: Train Loss=0.0128, Train Spearman=0.6753, Val Loss=0.0519, Val Spearman=0.3923, LR=7.8125e-05
Epoch 88: Train Loss=0.0131, Train Spearman=0.6717, Val Loss=0.0523, Val Spearman=0.3919, LR=7.8125e-05
Epoch 89: Train Loss=0.0137, Train Spearman=0.6781, Val Loss=0.0531, Val Spearman=0.3903, LR=3.90625e-05
Epoch 90: Train Loss=0.0128, Train Spearman=0.6807, Val Loss=0.0533, Val Spearman=0.3886, LR=3.90625e-05
Epoch 91: Train Loss=0.0141, Train Spearman=0.6726, Val Loss=0.0534, Val Spearman=0.3888, LR=3.90625e-05
Early stopping triggered.

In [46]:
# Show current ESM-based predictions.
df_pred[['mutant', 'DMS_score_predicted']].head(n=10)

  mutant  DMS_score_predicted
0    V1D             0.517606
1    V1Y             0.671239
2    V1C             0.204429
3    V1A             0.527578
4    V1E             0.507166
5    V1W             0.308169
6    V1T             0.422611
7    V1R             0.323677
8    V1Q             0.470055
9    V1S             0.614710

In [47]:
# Save predictions to .csv.
df_pred[['mutant', 'DMS_score_predicted']].to_csv('test_predictions.csv', index=False)

In [48]:
group_number = "1"

with open("GroupName.txt", "w") as f:
    f.write(group_number.strip() + "\n")

print("Saved GroupName.txt")

Saved GroupName.txt

In [49]:
api_key = "df303a548bec1afcff7d7196650c5396cfa74c94a8be5357043602dcc7537ba7"

with open("APIKey.txt", "w") as f:
    f.write(api_key.strip() + "\n")

print("Saved APIKey.txt")

Saved APIKey.txt

## 3. Select Query for Next Round

In [50]:
# Show prediction distribution.
df_pred.sort_values('DMS_score_predicted', ascending=False)

,mutant,sequence,DMS_score_predicted
10966,D637K,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,8.713370e-01
4741,P285K,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,8.434619e-01
10384,T606K,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,8.382987e-01
10375,T606Q,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,8.363634e-01
213,P12G,MVNEARGNSSLNGCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,8.307633e-01
...,...,...,...
3200,I181P,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,3.732108e-33
2674,L149D,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,7.339934e-34
9925,W582P,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,3.354780e-34
2733,A154D,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,3.146094e-34
3673,L213P,MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...,3.593616e-39

In [51]:
# Write mutants with top ten DMS scores to .txt file.
df_top_ten = df_pred.sort_values('DMS_score_predicted', ascending=False).head(n=10)
df_top_ten.to_csv('top10.txt', columns=['mutant'], index=False, header=False)
print(df_top_ten)

      mutant                                           sequence  \
10966  D637K  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
4741   P285K  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
10384  T606K  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
10375  T606Q  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
213     P12G  MVNEARGNSSLNGCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
280     E15N  MVNEARGNSSLNPCLNGSASSGSESSKDSSRCSTPGLDPERHERLR...
7206   S439N  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
10990  T638I  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
225     P12Y  MVNEARGNSSLNYCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...
8994   L533Q  MVNEARGNSSLNPCLEGSASSGSESSKDSSRCSTPGLDPERHERLR...

       DMS_score_predicted
10966             0.871337
4741              0.843462
10384             0.838299
10375             0.836363
213               0.830763
280               0.818689
7206              0.812668
10990             0.812659
225               0.809124
8994              0.800164

In [52]:
# Example: randomly select 100 test variants to be queried.
# Note: Random selection may not be a good strategy
# TODO: Select query mutants for the next round based on your own criteria

queries = np.random.choice(df_test.mutant.values, size=100, replace=False)
queries

array(['D401M', 'K355V', 'K104M', 'S25Y', 'L210V', 'Q259T', 'Y118S',
       'G312D', 'Q508N', 'N619G', 'D187E', 'C130D', 'R356V', 'T450W',
       'V635N', 'Q647P', 'A84F', 'A208P', 'R40E', 'S429Q', 'D56F',
       'L125M', 'V573L', 'A586L', 'L61W', 'F515K', 'I279P', 'I111A',
       'E552W', 'P555C', 'E600F', 'R43H', 'I279A', 'D494S', 'K145A',
       'L346M', 'R43P', 'R369V', 'G498T', 'F514R', 'L149F', 'V268W',
       'Q277A', 'S393N', 'E299D', 'P571M', 'P66S', 'Y403P', 'I293D',
       'V635P', 'V430P', 'V634P', 'N11Q', 'Y375R', 'R518L', 'A352D',
       'E135H', 'K371H', 'S604G', 'Y188P', 'L524C', 'A291Q', 'V282A',
       'L641F', 'G161L', 'I478W', 'E46T', 'S368H', 'D91T', 'E46G',
       'V621C', 'N323A', 'R49E', 'V1T', 'L404S', 'S604L', 'V542I',
       'N629I', 'V449K', 'T548L', 'K408H', 'V268T', 'D584V', 'K272P',
       'S392K', 'T68R', 'K413Y', 'K355G', 'E325T', 'S17Y', 'H200R',
       'Q146T', 'K272W', 'S492R', 'E299C', 'F383C', 'S19C', 'W164I',
       'E379W', 'L399Y'], dtype=object)

In [53]:
with open('query.txt', 'w') as f:
  for mutant in queries:
    f.write(mutant+'\n')